contacts = [
    {'nama': 'RIZQI WALDY BUAMONA', 'email': 'rizqi.waldy@kemenimipas.go.id'},
    {'nama': 'RIZQI WIJAYA', 'email': 'rizqi.wijaya98@kemenimipas.go.id'},
    {'nama': 'RIZQI ZULKARNAIN', 'email': 'rizqi.zulkarnain92@kemenimipas.go.id'},
    {'nama': 'RIZQIA SACHARINA', 'email': 'rizqia.sacharina@kemenimipas.go.id'},
    {'nama': "RIZQIYATUS SA'ADAH", 'email': 'rizqiyatus.saadah02@kemenimipas.go.id'},
    {'nama': 'RIZQO LAILA NUZULLA', 'email': 'rizqo.laila@kemenimipas.go.id'},
    {'nama': 'RIZQO SATRIA ALAM', 'email': 'rizqo.satria.alam93@kemenimipas.go.id'},
    {'nama': 'RIZQON ADHIIMU', 'email': 'rizqon.adhiimu05@kemenimipas.go.id'},
    {'nama': 'RIZQ ADYATMA SINULINGGA', 'email': 'rizqsinulingga45@gmail.com'},
    {'nama': 'RIZQY DWI NURROCHMAN', 'email': 'rizqy.dwi.nurrochman99@kemenimipas.go.id'},
    {'nama': 'RIZQY HIDAYAT LATUKAU', 'email': 'rizqy.hidayat.latukau00@kemenimipas.go.id'},
    {'nama': 'RIZQY KARYANDI AMALIA', 'email': 'rizqy.karyandi@kemenimipas.go.id'},
    {'nama': 'RIZQY VEGA PRATAMA', 'email': 'rizqy.vega@kemenimipas.go.id'},
    {'nama': 'RIZTI RIADI', 'email': 'rizti.riadi@kemenimipas.go.id'},
    {'nama': 'RIZWAN BIN KHAMIS', 'email': 'rizwan.bin.khamis98@kemenimipas.go.id'},
    {'nama': 'RIZWAN RIZKI PUTRA', 'email': 'rizwan.rizki@kemenimipas.go.id'},
    {'nama': 'RIZWAN SUANDI', 'email': 'rizwan.suandi82@kemenimipas.go.id'},
    {'nama': 'RIZWAN', 'email': 'rizwan@kemenimipas.go.id'},
    {'nama': 'RIZWANA DIAZ HAYUNING GITA', 'email': 'rizwana.diaz.hayuning.gita01@kemenimipas.go.id'},
    {'nama': 'RIZWAR AMIN', 'email': 'rizwar.amin05@kemenimipas.go.id'},
    {'nama': 'RIZYA BEELYADA PUALILLIN', 'email': 'rizya.beelyada.pualillin06@kemenimipas.go.id'},
    {'nama': 'RIZYANA AMANTIDINDA', 'email': 'rizyana.amantidinda05@kemenimipas.go.id'},
    {'nama': 'RIZZA KURNIAWAN', 'email': 'rizza.kurniawan90@kemenimipas.go.id'},
    {'nama': 'RIZZA NURKHARISMA RACHMAT, S.T', 'email': 'rizza.nurkharisma@kemenimipas.go.id'},
    {'nama': 'RIZZAL ARBI FANANI', 'email': 'rizzal.arbi@kemenimipas.go.id'},
    {'nama': 'RM. ALVIAN AZIZ', 'email': 'rm.alvian.aziz01@kemenimipas.go.id'},
    {'nama': 'RM DWI SOERYO POETRO', 'email': 'rm.dwi.soeryo.poetro80@kemenimipas.go.id'},
    {'nama': 'RMS.ALDIANSYAH', 'email': 'rms.aldiansyah95@kemenimipas.go.id'},
    {'nama': 'RO ASI CARLOS MANGAPUL MANURUNG', 'email': 'ro.asi.carlos.mangapul.manurung02@kemenimipas.go.id'},
    {'nama': 'ROARGA RUBBERT SIAHAAN, S.E.', 'email': 'roarga.rubbert@kemenimipas.go.id'},
    {'nama': 'ROAS SHADIQI', 'email': 'roas.shadiqi99@kemenimipas.go.id'},
    {'nama': 'ROBBI ABDI WIGUNA', 'email': 'robbi.abdi.wiguna93@kemenimipas.go.id'},
    {'nama': 'ROBBI MUHAMMAD ILHAMI', 'email': 'robbi.muhammad.ilhami97@kemenimipas.go.id'},
    {'nama': 'ROBBI RIVANDI', 'email': 'robbi.rivandi98@kemenimipas.go.id'},
    {'nama': 'ROBBI YATULLAH', 'email': 'robbi.yatullah@kemenimipas.go.id'},
    {'nama': 'ROBBY ADHA HARDIANTO', 'email': 'robby.adha.hardianto00@kemenimipas.go.id'},
    {'nama': 'ROBBY ADRIANSYAH SIREGAR', 'email': 'robby.adriansyah.siregar85@kemenimipas.go.id'},
    {'nama': 'ROBBY ADRIANSYAH', 'email': 'robby.adriansyah971@kemenimipas.go.id'},
    {'nama': 'ROBBY ANUGERAH SUCIPTO', 'email': 'robby.anugerah.sucipto97@kemenimipas.go.id'},
    {'nama': 'ROBBY ANUGRAH AMANDA', 'email': 'robby.anugrah.amanda94@kemenimipas.go.id'},
    {'nama': 'ROBBY ARDINATA, S.E.', 'email': 'robby.ardinata89@kemenimipas.go.id'},
    {'nama': 'ROBBY ARMUNANTO, S.E.', 'email': 'robby.armunanto@kemenimipas.go.id'},
    {'nama': 'ROBBY BERNAND SIJABAT', 'email': 'robby.bernand.sijabat83@kemenimipas.go.id'},
    {'nama': 'ROBBY CHANDRA', 'email': 'robby.chandra98@kemenimipas.go.id'},
    {'nama': 'ROBBY FEBRINALDI', 'email': 'robby.febrinaldi99@kemenimipas.go.id'},
    {'nama': 'ROBBY FERDIANSYAH ARIF', 'email': 'robby.ferdiansyah.arif03@kemenimipas.go.id'},
    {'nama': 'ROBBY HARVIANDI RAHMAN', 'email': 'robby.harviandi.rahman90@kemenimipas.go.id'},
    {'nama': 'ROBBY KRISNA PRAHMADIKA', 'email': 'robby.krisna.prahmadika92@kemenimipas.go.id'},
    {'nama': 'ROBBY KURNIA PUTRA', 'email': 'robby.kurnia.putra95@kemenimipas.go.id'},
    {'nama': 'ROBBY KURNIAWAN ZEKRI', 'email': 'robby.kurniawan.zekri95@kemenimipas.go.id'},
    {'nama': 'ROBBY KURNIAWAN', 'email': 'robby.kurniawan98@kemenimipas.go.id'},
    {'nama': 'ROBBY LOMBOAN', 'email': 'robby.lomboan@kemenimipas.go.id'},
    {'nama': 'ROBBY MARLEY', 'email': 'robby.marley99@kemenimipas.go.id'},
    {'nama': 'ROBBY MARTEJA', 'email': 'robby.marteja@kemenimipas.go.id'},
    {'nama': 'ROBBY MULIADI', 'email': 'robby.muliadi86@kemenimipas.go.id'},
    {'nama': 'ROBBY MUSTIKA', 'email': 'robby.mustika86@kemenimipas.go.id'},
    {'nama': 'ROBBY NOVRIYAN', 'email': 'robby.novriyan@kemenimipas.go.id'},
    {'nama': 'ROBBY PRAPTA YEZA', 'email': 'robby.prapta.yeza03@kemenimipas.go.id'},
    {'nama': 'ROBBY PRIMARIZAL', 'email': 'robby.primarizal@kemenimipas.go.id'},
    {'nama': 'ROBBY RAHMAN', 'email': 'robby.rahman99@kemenimipas.go.id'},
    {'nama': 'ROBBY ROBBANY', 'email': 'robby.robbany@kemenimipas.go.id'},
    {'nama': 'ROBBY SAFARI HADI', 'email': 'robby.safari@kemenimipas.go.id'},
    {'nama': 'ROBBY SASTRA', 'email': 'robby.sastra@kemenimipas.go.id'},
    {'nama': 'ROBBY SOEDARSONO', 'email': 'Robby.Soedarsono@kemenimipas.go.id'},
    {'nama': 'ROBBY SYAHPUTRA, S.Tr.Im', 'email': 'robby.syahputra99@kemenimipas.go.id'},
    {'nama': 'ROBBY TARIGAN', 'email': 'robby.tarigan82@kemenimipas.go.id'},
    {'nama': 'ROBBY TRI PANGESTU', 'email': 'robby.tri.pangestu00@kemenimipas.go.id'},
    {'nama': 'ROBBY TRISNO HADHI', 'email': 'robby.trisno@kemenimipas.go.id'},
    {'nama': 'ROBBY TRIYANTO. S', 'email': 'robby.triyanto@kemenimipas.go.id'},
    {'nama': 'ROBBY', 'email': 'robby80@kemenimipas.go.id'},
    {'nama': 'ROBBY', 'email': 'robby84@kemenimipas.go.id'},
    {'nama': 'ROBBYANOOR', 'email': 'robbyanoor@kemenimipas.go.id'},
    {'nama': 'ROBERMAN IMANUEL MANIK', 'email': 'roberman.imanuel.manik87@kemenimipas.go.id'},
    {'nama': 'ROBERT ALIDANI', 'email': 'robert.alidani@kemenimipas.go.id'},
    {'nama': 'ROBERT GUTIAWARMAN', 'email': 'robert.gutiawarman@kemenimipas.go.id'},
    {'nama': 'ROBERT JEK SOKOI', 'email': 'robert.jek.sokoi82@kemenimipas.go.id'},
    {'nama': 'ROBERT E JOHANIS', 'email': 'robert.johanis@kemenimipas.go.id'},
    {'nama': 'ROBERT NATALIUS TIBA', 'email': 'robert.nataliustiba@kemenimipas.go.id'},
    {'nama': 'ROBERT PARJUANGAN MARBUN', 'email': 'robert.parjuangan@kemenimipas.go.id'},
    {'nama': 'ROBERT PASKALIS KATIOP', 'email': 'Robert.Paskalis@kemenimipas.go.id'},
    {'nama': 'ROBERT PRATAMA ANJER DIMAS SAPUTRO', 'email': 'robert.pratama.anjer.dimas.saputro00@kemenimipas.go.id'},
    {'nama': 'ROBERT RAYKE', 'email': 'robert.rayke89@kemenimipas.go.id'},
    {'nama': 'ROBERT SANDRIA', 'email': 'robert.sandria@kemenimipas.go.id'},
    {'nama': 'ROBERT SIHALOHO', 'email': 'Robert.sihaloho@kemenimipas.go.id'},
    {'nama': 'ROBERT SINAGA', 'email': 'robert.sinaga79@kemenimipas.go.id'},
    {'nama': 'ROBERT STILMAN BILL ASBANU', 'email': 'robert.stilman@kemenimipas.go.id'},
    {'nama': 'ROBERT WIJAYA', 'email': 'robert.wijaya97@kemenimipas.go.id'},
    {'nama': 'ROBERT WILHEM DERRY', 'email': 'robert.wilhem.derry70@kemenimipas.go.id'},
    {'nama': 'ROBERTA RINI ISYUNTI', 'email': 'roberta.rini.isyunti70@kemenimipas.go.id'},
    {'nama': 'ROBERTH HERMAN KARSTEN', 'email': 'roberth.herman@kemenimipas.go.id'},
    {'nama': 'ROBERTH MALWEWAN', 'email': 'roberth.malwewan@kemenimipas.go.id'},
    {'nama': 'ROBERTH MASSA', 'email': 'roberth.massa85@kemenimipas.go.id'},
    {'nama': 'ROBERTHO FRANS KAISIEPO', 'email': 'robertho.frans.kaisiepo98@kemenimipas.go.id'},
    {'nama': 'ROBERTO ALI', 'email': 'roberto.ali95@kemenimipas.go.id'},
    {'nama': 'ROBERTO APRILIDAR FAUZI', 'email': 'roberto.aprilidar.fauzi99@kemenimipas.go.id'},
    {'nama': 'ROBERTO CAETANO FERREIRA PINTO', 'email': 'roberto.caetano.ferreira.pinto94@kemenimipas.go.id'},
    {'nama': 'ROBERTO CHRISTOV OGI ', 'email': 'roberto.christov.ogi99@kemenimipas.go.id'},
    {'nama': 'ROBERTO DHURAN DHURAN', 'email': 'roberto.dhuran.dhuran97@kemenimipas.go.id'},
    {'nama': 'ROBERTO G. MANEK LIURAI', 'email': 'roberto.g.manek.liurai00@kemenimipas.go.id'},
    {'nama': 'ROBERTO NAIBAHO', 'email': 'roberto.naibaho97@kemenimipas.go.id'},
    {'nama': 'ROBERTO SIAHAYA', 'email': 'roberto.siahaya76@kemenimipas.go.id'},
    {'nama': 'ROBERTO SITANGGANG', 'email': 'roberto.sitanggang97@kemenimipas.go.id'},
    {'nama': 'ROBERTO SULANDRY', 'email': 'roberto.sulandry83@kemenimipas.go.id'},
    {'nama': 'ROBERTO TONAPA LINO', 'email': 'roberto.tonapa.lino98@kemenimipas.go.id'},
    {'nama': 'ROBERTON LUMBAN RAJA', 'email': 'roberton.lumban.raja93@kemenimipas.go.id'},
    {'nama': 'ROBERTSON ROY RUMAYAUW', 'email': 'robertson.roy.rumayauw78@kemenimipas.go.id'},
    {'nama': 'ROBERTUS BELARMINO MELE', 'email': 'robertus.belarmino.mele89@kemenimipas.go.id'},
    {'nama': 'ROBERTUS DANANG SUBROTO', 'email': 'robertus.danang.subroto99@kemenimipas.go.id'},
    {'nama': 'ROBERTUS FERDIAN AUGUS SIDHARTA', 'email': 'Robertus.ferdian@kemenimipas.go.id'},
    {'nama': 'ROBERTUS IWAN BUDIARTO', 'email': 'robertus.iwan@kemenimipas.go.id'},
    {'nama': 'ROBERTUS KUTANGGAS', 'email': 'robertus.kutanggas74@kemenimipas.go.id'},
    {'nama': 'ROBERTUS WIJAYA', 'email': 'robertus.wijaya@kemenimipas.go.id'},
    {'nama': 'ROBET KINASIH', 'email': 'robet.kinasih94@kemenimipas.go.id'},
    {'nama': 'ROBI ABDI WIRANATA KRAMA', 'email': 'robi.abdi@kemenimipas.go.id'},
    {'nama': 'ROBI EKA SAPUTRA', 'email': 'robi.eka@kemenimipas.go.id'},
    {'nama': 'ROBI FIRDAUS', 'email': 'robi.firdaus@kemenimipas.go.id'},
    {'nama': 'ROBI GUNAWAN PURBA', 'email': 'robi.gunawan.purba98@kemenimipas.go.id'},
    {'nama': 'ROBI HERMAWAN SUSANTO', 'email': 'robi.hermawan.susanto00@kemenimipas.go.id'},
    {'nama': 'ROBI HIDAYAT', 'email': 'robi.hidayat89@kemenimipas.go.id'},
    {'nama': 'ROBI ILYASA', 'email': 'robi.ilyasa03@kemenimipas.go.id'},
    {'nama': 'ROBI IRAWAN', 'email': 'robi.irawan88@kemenimipas.go.id'},
    {'nama': 'MUHAMMAD ROBI MAULANA', 'email': 'robi.maulana@kemenimipas.go.id'},
    {'nama': 'ROBI RAHMADI', 'email': 'robi.rahmadi86@kemenimipas.go.id'},
    {'nama': 'ROBI SANDI AKBAR', 'email': 'robi.sandi@kemenimipas.go.id'},
    {'nama': 'ROBI SETIAJI', 'email': 'robi.setiaji97@kemenimipas.go.id'},
    {'nama': 'ROBI SETIAWAN TRIDESIA', 'email': 'robi.setiawan.tridesia97@kemenimipas.go.id'},
    {'nama': 'ROBI SUGARA', 'email': 'robi.sugara97@kemenimipas.go.id'},
    {'nama': 'ROBI SYAPUTRA', 'email': 'robi.syaputra99@kemenimipas.go.id'},
    {'nama': 'ROBI WAHYUDI', 'email': 'robi.wahyudi@kemenimipas.go.id'},
    {'nama': 'ROBI WIBAWA WINATA', 'email': 'robi.wibawa@kemenimipas.go.id'},
    {'nama': 'ROBI YUHENDRI, A.Md', 'email': 'robi.yuhendri81@kemenimipas.go.id'},
    {'nama': 'ROBI', 'email': 'robi89@kemenimipas.go.id'},
    {'nama': 'ROBI', 'email': 'robi90@kemenimipas.go.id'},
    {'nama': 'ROBIANTA BARUS', 'email': 'robianta.barus97@kemenimipas.go.id'},
    {'nama': 'ROBIANTO, S.H', 'email': 'robianto71@kemenimipas.go.id'},
    {'nama': 'ROBIANUR', 'email': 'robianur93@kemenimipas.go.id'},
    {'nama': 'ROBIE SANJAYA', 'email': 'robie.sanjaya03@kemenimipas.go.id'},
    {'nama': 'ROBIL', 'email': 'robil94@kemenimipas.go.id'},
    {'nama': 'ROBIN AGUSSAPUTRA', 'email': 'robin.agussaputra@kemenimipas.go.id'},
    {'nama': 'ROBIN HASIHOLAN HUTABARAT', 'email': 'robin.hasiholan.hutabarat92@kemenimipas.go.id'},
    {'nama': 'ROBIN PUTUT HATTARI ARDRIYUNAN', 'email': 'robin.putut.hattari.ardriyunan90@kemenimipas.go.id'},
    {'nama': 'ROBIN SIMAMORA', 'email': 'robin.simamora67@kemenimipas.go.id'},
    {'nama': 'ROBIN ZYU AKBAR', 'email': 'robin.zyu.akbar96@kemenimipas.go.id'},
    {'nama': 'ROBIN', 'email': 'robin96@kemenimipas.go.id'},
    {'nama': 'ROBINSAR BANJAR NAHOR', 'email': 'robinsar.banjar.nahor95@kemenimipas.go.id'},
    {'nama': 'ROBINSON ALEXANDER KALE', 'email': 'robinson.alexander@kemenimipas.go.id'},
    {'nama': 'ROBINSON HASUDUNGAN SIREGAR', 'email': 'robinson.hasudungan@kemenimipas.go.id'},
    {'nama': 'ROBINSON PERANGIN ANGIN', 'email': 'robinson.perangin@kemenimipas.go.id'},
    {'nama': 'ROBINSON SINURAT', 'email': 'robinson.sinurat@kemenimipas.go.id'},
    {'nama': 'ROBINSON SUFARNO MADJOWA', 'email': 'robinson.sufarno.madjowa96@kemenimipas.go.id'},
    {'nama': 'ROBINSON TAMPUBOLON', 'email': 'robinson.tampubolon@kemenimipas.go.id'},
    {'nama': 'ROBINSON TULONG', 'email': 'robinson.tulong@kemenimipas.go.id'},
    {'nama': 'ROBINSON, SE', 'email': 'robinson91@kemenimipas.go.id'},
    {'nama': 'ROBINSON', 'email': 'robinson97@kemenimipas.go.id'},
    {'nama': 'ROBINTANG GANDA TUA SITORUS', 'email': 'robintang.ganda.tua.sitorus05@kemenimipas.go.id'},
    {'nama': 'ROBITA ISLAMI', 'email': 'robita.islami91@kemenimipas.go.id'},
    {'nama': 'ROBITHOH ANAM ULINNAJA', 'email': 'robithoh.anam@kemenimipas.go.id'},
    {'nama': 'ROBIY FANCANDRA', 'email': 'robiy.fancandra98@kemenimipas.go.id'},
    {'nama': 'ROBIYANTORO', 'email': 'robiyantoro90@kemenimipas.go.id'},
    {'nama': 'ROBIYANUR', 'email': 'robiyanur94@kemenimipas.go.id'},
    {'nama': 'ROBY AFRIADI', 'email': 'roby.afriadi87@kemenimipas.go.id'},
    {'nama': 'ROBY AGI PUTRA', 'email': 'roby.agi.putra00@kemenimipas.go.id'},
    {'nama': 'ROBY AKBAR WANARDI', 'email': 'roby.akbar.wanardi98@kemenimipas.go.id'},
    {'nama': 'ROBY ALDYANTO', 'email': 'roby.aldyanto94@kemenimipas.go.id'},
    {'nama': 'ROBY ARYANTO', 'email': 'roby.aryanto97@kemenimipas.go.id'},
    {'nama': 'ROBY AZHARI', 'email': 'roby.azhari@kemenimipas.go.id'},
    {'nama': 'ROBY CHRISTIAN HUTASOIT', 'email': 'roby.christian.hutasoit98@kemenimipas.go.id'},
    {'nama': 'ROBY EDUARD THERIK', 'email': 'roby.eduard@kemenimipas.go.id'},
    {'nama': 'ROBY FERNANDEZ', 'email': 'roby.fernandez@kemenimipas.go.id'},
    {'nama': 'ROBY FIRLANA', 'email': 'roby.firlana99@kemenimipas.go.id'},
    {'nama': 'ROBY GINANZAR TIRTA PRAWIRA', 'email': 'roby.ginanzar.tirta.prawira91@kemenimipas.go.id'},
    {'nama': 'ROBY HARDIANSYAH', 'email': 'roby.hardiansyah@kemenimipas.go.id'},
    {'nama': 'ROBY IKHSAN', 'email': 'roby.ikhsan78@kemenimipas.go.id'},
    {'nama': 'ROBY KURNIAWAN', 'email': 'roby.kurniawan800@kemenimipas.go.id'},
    {'nama': 'ROBY NUANSA', 'email': 'roby.nuansa92@kemenimipas.go.id'},
    {'nama': 'ROBY PARDOMUAN CIBRO, S.E.', 'email': 'roby.pardomuan@kemenimipas.go.id'},
    {'nama': 'ROBY ROZALI', 'email': 'roby.rozali@kemenimipas.go.id'},
    {'nama': 'ROBY TRI NUGROHO', 'email': 'roby.tri.nugroho95@kemenimipas.go.id'},
    {'nama': 'ROCHANA ERNAWATI', 'email': 'rochana.ernawati70@kemenimipas.go.id'},
    {'nama': 'ROCHMAD NUR KHOLIS', 'email': 'rochmad.nur.kholis97@kemenimipas.go.id'},
    {'nama': 'ROCHMAD SAHID, S.E.,M.A.P.', 'email': 'rochmad.sahid@kemenimipas.go.id'},
    {'nama': 'ROCHMAD SEDIJONO', 'email': 'rochmad.sedijono68@kemenimipas.go.id'},
    {'nama': 'ROCHMAN NUGROHO', 'email': 'rochman.nugroho95@kemenimipas.go.id'},
    {'nama': 'ROCHMANI WIKA HASTUNINGRUM', 'email': 'rochmani.wika.hastuningrum93@kemenimipas.go.id'},
    {'nama': 'ROCHUS GONSALEZ NANDO BANA', 'email': 'rochus.gonsalez.nando.bana97@kemenimipas.go.id'},
    {'nama': 'ROCHY NANANG SAPUTRA', 'email': 'rochy.nanang.saputra68@kemenimipas.go.id'},
    {'nama': 'ROCKY FEBRIAN', 'email': 'rocky.febrian05@kemenimipas.go.id'},
    {'nama': 'ROCKY FRIEZA', 'email': 'rocky.frieza01@kemenimipas.go.id'},
    {'nama': 'ROCKY JAYA SAPUTRA', 'email': 'rocky.jaya@kemenimipas.go.id'},
    {'nama': 'ROCKY LARENGGAM', 'email': 'rocky.larenggam@kemenimipas.go.id'},
    {'nama': 'ROCKY MARCIANO SINE', 'email': 'rocky.marciano@kemenimipas.go.id'},
    {'nama': 'ROCKY MARKIANO BANGUN', 'email': 'rocky.markiano@kemenimipas.go.id'},
    {'nama': 'ROCKY OKTAVIANUS MISDJAN', 'email': 'rocky.oktavianus@kemenimipas.go.id'},
    {'nama': 'ROCKY RIVALDO', 'email': 'rocky.rivaldo97@kemenimipas.go.id'},
    {'nama': 'ROCKY ROLAND BUNGSU LAY', 'email': 'rocky.roland.bungsu.lay92@kemenimipas.go.id'},
    {'nama': 'ROCKY SIMANJUNTAK', 'email': 'rocky.simanjuntak97@kemenimipas.go.id'},
    {'nama': 'ROCKY WAJONG', 'email': 'rocky.wajong@kemenimipas.go.id'},
    {'nama': 'RODASNI SIDAURUK', 'email': 'rodasni.sidauruk91@kemenimipas.go.id'},
    {'nama': 'RODESTA DEVEGA KEHI', 'email': 'rodesta.kehi@kemenimipas.go.id'},
    {'nama': 'RODHAN BIJAKSA', 'email': 'rodhan.bijaksa94@kemenimipas.go.id'},
    {'nama': 'RODHIATI SIREGAR', 'email': 'rodhiati.siregar@kemenimipas.go.id'},
    {'nama': 'RODHIYA NOOR FAJRI', 'email': 'rodhiya.noor@kemenimipas.go.id'},
    {'nama': 'RODHIYATNO', 'email': 'rodhiyatno74@kemenimipas.go.id'},
    {'nama': 'RODI ERNADO', 'email': 'rodi.ernado@kemenimipas.go.id'},
    {'nama': 'RODIAH', 'email': 'rodiah85@kemenimipas.go.id'},
    {'nama': 'RODIAN, S.H.', 'email': 'rodian89@kemenimipas.go.id'},
    {'nama': 'RODIATUL MARDIYAH', 'email': 'rodiatul.mardiyah95@kemenimipas.go.id'},
    {'nama': 'RODIYAH', 'email': 'rodiyah68@kemenimipas.go.id'},
    {'nama': 'RODJOSH TIO PUTRA L. TOBING', 'email': 'rodjosh.tio.putra.l.tobing98@kemenimipas.go.id'},
    {'nama': 'RODLIN, S.E.', 'email': 'rodlin88@kemenimipas.go.id'},
    {'nama': 'RODY AHMAD TOYIB', 'email': 'rody.ahmad.toyib00@kemenimipas.go.id'},
    {'nama': 'RODY WARDANIAL', 'email': 'rody.wardanial@kemenimipas.go.id'},
    {'nama': 'ROECY RANTIKA', 'email': 'roecy.rantika@kemenimipas.go.id'},
    {'nama': 'ROFI HANSYAH', 'email': 'rofi.hansyah@kemenimipas.go.id'}
]
