contacts = [
    {'nama': 'RIZAL BALANGO', 'email': 'rizal.balango90@kemenimipas.go.id'},
    {'nama': 'RIZAL BUDI RAHARJO', 'email': 'rizal.budi.raharjo96@kemenimipas.go.id'},
    {'nama': 'RIZAL BUDI PRASETYO', 'email': 'rizal.budi@kemenimipas.go.id'},
    {'nama': 'RIZAL CATUR MAPRIONO', 'email': 'rizal.catur@kemenimipas.go.id'},
    {'nama': 'RIZAL CHANDRAWINATA', 'email': 'rizal.chandrawinata97@kemenimipas.go.id'},
    {'nama': 'RIZAL CHORNIAWAN AZHARY', 'email': 'rizal.chorniawan.azhary98@kemenimipas.go.id'},
    {'nama': 'RIZAL DASIR', 'email': 'rizal.dasir@kemenimipas.go.id'},
    {'nama': 'RIZAL DAVID PAMIKIRAN', 'email': 'rizal.david@kemenimipas.go.id'},
    {'nama': 'RIZAL DJO', 'email': 'rizal.djo93@kemenimipas.go.id'},
    {'nama': 'RIZAL EKA PRASETYA MADURAGA', 'email': 'rizal.eka.prasetya.maduraga89@kemenimipas.go.id'},
    {'nama': 'M RIZAL EKO ABRIANTO', 'email': 'rizal.eko@kemenimipas.go.id'},
    {'nama': 'RIZAL ERMAWAN', 'email': 'rizal.ermawan87@kemenimipas.go.id'},
    {'nama': 'RIZAL FADHILAH', 'email': 'rizal.fadhilah01@kemenimipas.go.id'},
    {'nama': 'RIZAL FADHILLAH', 'email': 'rizal.fadhillah96@kemenimipas.go.id'},
    {'nama': 'RIZAL FADILLAH', 'email': 'rizal.fadillah99@kemenimipas.go.id'},
    {'nama': 'RIZAL FAHLEPI', 'email': 'rizal.fahlepi97@kemenimipas.go.id'},
    {'nama': 'RIZAL FAHLIVI', 'email': 'rizal.fahlivi@kemenimipas.go.id'},
    {'nama': 'RIZAL FAHMI', 'email': 'rizal.fahmi89@kemenimipas.go.id'},
    {'nama': 'RIZAL FAHRUL GUNAWAN', 'email': 'rizal.fahrul.gunawan01@kemenimipas.go.id'},
    {'nama': 'RIZAL FAITFUL ROMADONY', 'email': 'rizal.faitful.romadony70@kemenimipas.go.id'},
    {'nama': 'RIZAL FATHONI', 'email': 'rizal.fathoni@kemenimipas.go.id'},
    {'nama': 'RIZAL FATONI', 'email': 'rizal.fatoni02@kemenimipas.go.id'},
    {'nama': 'RIZAL FITROH DWI WIDODO, S.Tr.Im.', 'email': 'rizal.fitroh.dwi.widodo01@kemenimipas.go.id'},
    {'nama': 'RIZAL FUAD HERLAMBANG', 'email': 'rizal.fuad.herlambang99@kemenimipas.go.id'},
    {'nama': 'RIZAL HAMDI SYABANI', 'email': 'rizal.hamdi.syabani03@kemenimipas.go.id'},
    {'nama': 'RIZAL HARTONO', 'email': 'rizal.hartono@kemenimipas.go.id'},
    {'nama': 'RIZAL HERMAWAN', 'email': 'rizal.hermawan98@kemenimipas.go.id'},
    {'nama': 'RIZAL HIDAYAT', 'email': 'rizal.hidayat02@kemenimipas.go.id'},
    {'nama': 'RIZAL HIDAYATULLOH', 'email': 'rizal.hidayatulloh01@kemenimipas.go.id'},
    {'nama': 'RIZAL HOTMA NEGARA SOHUTURON NAPITUPULU', 'email': 'rizal.hotma.negara.sohuturon.napitupulu96@kemenimipas.go.id'},
    {'nama': 'RIZAL IBRAHIM', 'email': 'rizal.ibrahim88@kemenimipas.go.id'},
    {'nama': 'RIZAL IBRAHIM', 'email': 'rizal.ibrahim94@kemenimipas.go.id'},
    {'nama': 'RIZAL JACKSON HUTASOIT', 'email': 'rizal.jackson.hutasoit98@kemenimipas.go.id'},
    {'nama': 'RIZAL JUANG SAPUTRA', 'email': 'rizal.juang.saputra99@kemenimipas.go.id'},
    {'nama': 'RIZAL KRESNANDA PRASETYA', 'email': 'rizal.kresnanda.prasetya95@kemenimipas.go.id'},
    {'nama': 'RIZAL KURNIA FAHLEVI', 'email': 'rizal.kurnia.fahlevi98@kemenimipas.go.id'},
    {'nama': 'RIZAL KURNIAWAN', 'email': 'rizal.kurniawan97@kemenimipas.go.id'},
    {'nama': 'RIZAL LAMBOK SIANIPAR', 'email': 'rizal.lambok.sianipar94@kemenimipas.go.id'},
    {'nama': 'RIZAL LAZUARDINUR', 'email': 'rizal.lazuardinur87@kemenimipas.go.id'},
    {'nama': 'RIZAL LISAMORA. AD', 'email': 'rizal.lisamora@kemenimipas.go.id'},
    {'nama': 'RIZAL. M', 'email': 'rizal.m@kemenimipas.go.id'},
    {'nama': 'RIZAL MADANI', 'email': 'rizal.madani92@kemenimipas.go.id'},
    {'nama': 'RIZAL MATTA RANGGA', 'email': 'rizal.matta.rangga00@kemenimipas.go.id'},
    {'nama': 'RIZAL MAULANA', 'email': 'rizal.maulana885@kemenimipas.go.id'},
    {'nama': 'RIZAL MAULANA', 'email': 'rizal.maulana91@kemenimipas.go.id'},
    {'nama': 'RIZAL MESFER', 'email': 'rizal.mesfer@kemenimipas.go.id'},
    {'nama': 'RIZAL MULIADI', 'email': 'rizal.muliadi69@kemenimipas.go.id'},
    {'nama': 'RIZAL MULYADI', 'email': 'rizal.mulyadi02@kemenimipas.go.id'},
    {'nama': 'RIZAL MUSTAQIM', 'email': 'rizal.mustaqim94@kemenimipas.go.id'},
    {'nama': 'RIZAL MUTTAQIEN , S.H.', 'email': 'rizal.muttaqien90@kemenimipas.go.id'},
    {'nama': 'RIZAL NOVI ARDIANTO', 'email': 'rizal.novi.ardianto96@kemenimipas.go.id'},
    {'nama': 'RIZAL NUR IKHSANI', 'email': 'rizal.nur.ikhsani02@kemenimipas.go.id'},
    {'nama': 'RIZAL NUR MUHAMMAD', 'email': 'rizal.nur.muhammad89@kemenimipas.go.id'},
    {'nama': 'RIZAL PAHLEFI', 'email': 'rizal.pahlefi86@kemenimipas.go.id'},
    {'nama': 'RIZAL PAHLEVI', 'email': 'rizal.pahlevi87@kemenimipas.go.id'},
    {'nama': 'RIZAL PRANTAMA DIMAS SAPUTRA', 'email': 'rizal.prantama.dimas.saputra99@kemenimipas.go.id'},
    {'nama': 'RIZAL RAHMADI', 'email': 'rizal.rahmadi98@kemenimipas.go.id'},
    {'nama': 'RIZAL RAHMAT DARMAWAN', 'email': 'rizal.rahmat.darmawan94@kemenimipas.go.id'},
    {'nama': 'RIZAL RAMADHAN', 'email': 'rizal.ramadhan99@kemenimipas.go.id'},
    {'nama': 'RIZAL RIVAI', 'email': 'rizal.rivai@kemenimipas.go.id'},
    {'nama': 'RIZAL RIZKY BAKHTIAR', 'email': 'rizal.rizky.bakhtiar01@kemenimipas.go.id'},
    {'nama': 'RIZAL SAEPUL AZIZ', 'email': 'rizal.saepul@kemenimipas.go.id'},
    {'nama': 'RIZAL SAPUTRA', 'email': 'rizal.saputra@kemenimipas.go.id'},
    {'nama': 'RIZAL SURYA SYAPUTRA', 'email': 'rizal.surya@kemenimipas.go.id'},
    {'nama': 'RIZAL SUSANTO KAU', 'email': 'rizal.susanto.kau84@kemenimipas.go.id'},
    {'nama': 'RIZAL SUYANTO', 'email': 'rizal.suyanto@kemenimipas.go.id'},
    {'nama': 'RIZAL SYAHRIAL AMINUDIN, S.Tr.Im.', 'email': 'rizal.syahrial.aminudin00@kemenimipas.go.id'},
    {'nama': 'RIZAL TALIB', 'email': 'rizal.talib03@kemenimipas.go.id'},
    {'nama': 'RIZAL WAHAB', 'email': 'rizal.wahab97@kemenimipas.go.id'},
    {'nama': 'RIZAL WAHYU SYAHPUTRA', 'email': 'rizal.wahyu.syahputra00@kemenimipas.go.id'},
    {'nama': 'RIZAL WAHYUDI', 'email': 'rizal.wahyudi93@kemenimipas.go.id'},
    {'nama': 'RIZAL WAHYUDIANTO', 'email': 'rizal.wahyudianto00@kemenimipas.go.id'},
    {'nama': 'RIZAL WALIYUDIN', 'email': 'rizal.waliyudin94@kemenimipas.go.id'},
    {'nama': 'RIZAL WILIANTO', 'email': 'rizal.wilianto94@kemenimipas.go.id'},
    {'nama': 'RIZAL WINA PRATAMA', 'email': 'rizal.wina.pratama01@kemenimipas.go.id'},
    {'nama': 'RIZAL ZIBRAN', 'email': 'rizal.zibran98@kemenimipas.go.id'},
    {'nama': 'RIZAL', 'email': 'rizal@kemenimipas.go.id'},
    {'nama': 'RIZAL', 'email': 'rizal01@kemenimipas.go.id'},
    {'nama': 'RIZAL, S.H.', 'email': 'rizal71@kemenimipas.go.id'},
    {'nama': 'RIZAL', 'email': 'rizal73@kemenimipas.go.id'},
    {'nama': 'RIZAL', 'email': 'rizal77@kemenimipas.go.id'},
    {'nama': 'RIZAL', 'email': 'rizal80@kemenimipas.go.id'},
    {'nama': 'RIZAL', 'email': 'rizal82@kemenimipas.go.id'},
    {'nama': 'RIZAL', 'email': 'rizal92@kemenimipas.go.id'},
    {'nama': 'RIZAL', 'email': 'rizal98@kemenimipas.go.id'},
    {'nama': 'MUHAMMAD RIZALDI HARIS', 'email': 'rizaldi.haris@kemenimipas.go.id'},
    {'nama': 'RIZALDI KURNIAWAN', 'email': 'rizaldi.kurniawan90@kemenimipas.go.id'},
    {'nama': 'RIZALDI YAHYA', 'email': 'rizaldi.yahya93@kemenimipas.go.id'},
    {'nama': 'RIZALDO FERARI', 'email': 'rizaldo.ferari03@kemenimipas.go.id'},
    {'nama': 'RIZALDY MARTINO SELI', 'email': 'rizaldy.martino.seli98@kemenimipas.go.id'},
    {'nama': 'RIZAL FAHLEVI MUFTI MAHU', 'email': 'rizalfahlevi.muftimahu@kemenimipas.go.id'},
    {'nama': 'RIZALI NOR HIDAYATULLAH', 'email': 'rizali.nor@kemenimipas.go.id'},
    {'nama': 'RIZALLUL BADRI', 'email': 'rizallul.badri@kemenimipas.go.id'},
    {'nama': 'RIZAM HATAMI', 'email': 'rizam.hatami90@kemenimipas.go.id'},
    {'nama': 'RIZAM PRATAMA NUGRAHA', 'email': 'rizam.pratama.nugraha00@kemenimipas.go.id'},
    {'nama': 'RIZAM WISNU PAMUNGKAS', 'email': 'rizam.wisnu.pamungkas92@kemenimipas.go.id'},
    {'nama': 'MUHAMMAD RIZAN LUQMAN', 'email': 'rizan.luqman@kemenimipas.go.id'},
    {'nama': 'RIZANA RUKMANA PUTRA', 'email': 'rizana.rukmana.putra96@kemenimipas.go.id'},
    {'nama': 'RIZANI, SH', 'email': 'rizani69@kemenimipas.go.id'},
    {'nama': 'RIZAQ SILMI ABDJUL', 'email': 'rizaq.silmi.abdjul95@kemenimipas.go.id'},
    {'nama': 'RIZATUN HUSNI', 'email': 'rizatun.husni98@kemenimipas.go.id'},
    {'nama': 'RIZAWALDI', 'email': 'rizawaldizati@gmail.com'},
    {'nama': 'RIZDIYANTI FEBRIANI', 'email': 'rizdiyanti.febriani93@kemenimipas.go.id'},
    {'nama': 'RIZFAN DWIKA WIDIANTARA', 'email': 'rizfan.dwika.widiantara00@kemenimipas.go.id'},
    {'nama': 'RIZHA ASHARI', 'email': 'rizha.ashari@kemenimipas.go.id'},
    {'nama': 'RIZHA FEBRYAN, S.H.', 'email': 'rizha.febryan78@kemenimipas.go.id'},
    {'nama': 'RIZI AMALIA', 'email': 'rizi.amalia00@kemenimipas.go.id'},
    {'nama': 'RIZIEQ MUHAMAD AKBAR', 'email': 'rizieq.muhamad.akbar04@kemenimipas.go.id'},
    {'nama': 'RIZIKA AGUSTIN', 'email': 'rizika.agustin@kemenimipas.go.id'},
    {'nama': 'RIZKA AKBAR YUNANTO', 'email': 'rizka.akbar.yunanto00@kemenimipas.go.id'},
    {'nama': 'RIZKA APRILIA KHAIRUNNISA', 'email': 'rizka.aprilia@kemenimipas.go.id'},
    {'nama': 'RIZKA ARDHI PRADIKA', 'email': 'rizka.ardhi.pradika94@kemenimipas.go.id'},
    {'nama': 'RIZKA ASMARITA', 'email': 'rizka.asmarita97@kemenimipas.go.id'},
    {'nama': 'RIZKA AULIA', 'email': 'rizka.aulia05@kemenimipas.go.id'},
    {'nama': 'RIZKA AULIA, S.Kep., Ners.', 'email': 'rizka.aulia91@kemenimipas.go.id'},
    {'nama': 'RIZKA DESITANIA ROYANTI', 'email': 'rizka.desitania.royanti01@kemenimipas.go.id'},
    {'nama': 'RIZKA FARAMITASARI', 'email': 'rizka.faramitasari82@kemenimipas.go.id'},
    {'nama': 'RIZKA FIRDA AULIA', 'email': 'rizka.firda.aulia04@kemenimipas.go.id'},
    {'nama': 'RIZKA FRATIWI PUTRI', 'email': 'rizka.fratiwi@kemenimipas.go.id'},
    {'nama': 'RIZKA IRDHAWATI', 'email': 'rizka.irdhawati91@kemenimipas.go.id'},
    {'nama': 'RIZKA IWAN MUNARA', 'email': 'rizka.iwan.munara93@kemenimipas.go.id'},
    {'nama': 'RIZKA KARTIKA DEVI', 'email': 'rizka.kartika@kemenimipas.go.id'},
    {'nama': 'RIZKA MAHARANI', 'email': 'Rizka.Maharani@kemenimipas.go.id'},
    {'nama': 'RIZKA MARANTIKA', 'email': 'rizka.marantika03@kemenimipas.go.id'},
    {'nama': 'RIZKA MAULIDA', 'email': 'rizka.maulida94@kemenimipas.go.id'},
    {'nama': 'RIZKA MISY LINDA, A.Md.Kep', 'email': 'rizka.misy.linda92@kemenimipas.go.id'},
    {'nama': 'RIZKA PRIHANDANA NUGRAHA', 'email': 'rizka.prihandana.nugraha96@kemenimipas.go.id'},
    {'nama': 'RIZKA RACHMAWATI', 'email': 'rizka.rachmawati03@kemenimipas.go.id'},
    {'nama': 'RIZKA RAHMAHARYANTI', 'email': 'rizka.rahmaharyanti93@kemenimipas.go.id'},
    {'nama': 'RIZKA RIZAL FATAH JAINAHU', 'email': 'Rizka.Rizal@kemenimipas.go.id'},
    {'nama': 'RIZKA SADILAH', 'email': 'rizka.sadilah@kemenimipas.go.id'},
    {'nama': 'RIZKA SATRIA', 'email': 'rizka.satria92@kemenimipas.go.id'},
    {'nama': 'RIZKA VIONITA', 'email': 'rizka.vionita@kemenimipas.go.id'},
    {'nama': 'RIZKA YUSRINA', 'email': 'rizka.yusrina@kemenimipas.go.id'},
    {'nama': 'RIZKA', 'email': 'rizka89@kemenimipas.go.id'},
    {'nama': 'RIZKA, A.Md.Kep', 'email': 'rizka96@kemenimipas.go.id'},
    {'nama': 'M. RIZKAN NAFARIN', 'email': 'rizkan.nafarin@kemenimipas.go.id'},
    {'nama': 'RIZKAR HIDAYAT', 'email': 'rizkar.hidayat94@kemenimipas.go.id'},
    {'nama': 'RIZKI ABDURROHMAN', 'email': 'rizki.abdurrohman94@kemenimipas.go.id'},
    {'nama': 'RIZKI ADAM ERLANGGA', 'email': 'rizki.adam.erlangga01@kemenimipas.go.id'},
    {'nama': 'RIZKI ADHI WITANTO', 'email': 'rizki.adhi@kemenimipas.go.id'},
    {'nama': 'RIZKI ADIANTO S.H.', 'email': 'rizki.adianto96@kemenimipas.go.id'},
    {'nama': 'RIZKI ADINDA', 'email': 'rizki.adinda02@kemenimipas.go.id'},
    {'nama': 'RIZKI ADIPUTRA MEPA', 'email': 'rizki.adiputra@kemenimipas.go.id'},
    {'nama': 'RIZKI ADIYATI SRI UTAMI', 'email': 'rizki.adiyati.sri.utami88@kemenimipas.go.id'},
    {'nama': 'RIZKI AFRIANTO', 'email': 'rizki.afrianto01@kemenimipas.go.id'},
    {'nama': 'RIZKI AGUS FARDIAN', 'email': 'rizki.agus.fardian92@kemenimipas.go.id'},
    {'nama': 'RIZKI AGUS YOGA PRATAMA', 'email': 'rizki.agus.yoga.pratama86@kemenimipas.go.id'},
    {'nama': 'RIZKI AGUSTRIANSYAH', 'email': 'rizki.agustriansyah99@kemenimipas.go.id'},
    {'nama': 'RIZKI AKBAR', 'email': 'rizki.akbar@kemenimipas.go.id'},
    {'nama': 'RIZKI AKBAR', 'email': 'rizki.akbar936@kemenimipas.go.id'},
    {'nama': 'RIZKI AKBAR', 'email': 'rizki.akbar97@kemenimipas.go.id'},
    {'nama': 'RIZKI ALDILAH', 'email': 'rizki.aldilah03@kemenimipas.go.id'},
    {'nama': 'RIZKI ALFARIZI', 'email': 'rizki.alfarizi06@kemenimipas.go.id'},
    {'nama': 'RIZKI ALLEZA APRIANTA', 'email': 'rizki.alleza@kemenimipas.go.id'},
    {'nama': 'RIZKI ALUSY, S.H', 'email': 'rizki.alusy@kemenimipas.go.id'},
    {'nama': 'RIZKI AMALIA LAOLI', 'email': 'rizki.amalia.laoli95@kemenimipas.go.id'},
    {'nama': 'RIZKI AMELIA', 'email': 'rizki.amelia00@kemenimipas.go.id'},
    {'nama': 'RIZKI ANANDA', 'email': 'rizki.ananda@kemenimipas.go.id'},
    {'nama': 'RIZKI ANANDA', 'email': 'rizki.ananda00@kemenimipas.go.id'},
    {'nama': 'RIZKI ANANDA', 'email': 'rizki.ananda93@kemenimipas.go.id'},
    {'nama': 'RIZKI ANANDA', 'email': 'rizki.ananda98@kemenimipas.go.id'},
    {'nama': 'RIZKI ANANDA GINTING', 'email': 'Rizki.ananda990@kemenimipas.go.id'},
    {'nama': 'RIZKI ANANTA ILHAM', 'email': 'rizki.ananta.ilham97@kemenimipas.go.id'},
    {'nama': 'RIZKI ANDIKA MASYHUR', 'email': 'rizki.andika.masyhur95@kemenimipas.go.id'},
    {'nama': 'RIZKI ANDRIAN', 'email': 'rizki.andrian01@kemenimipas.go.id'},
    {'nama': 'RIZKI ANGGI WIRADANA', 'email': 'rizki.anggi.wiradana00@kemenimipas.go.id'},
    {'nama': 'RIZKI ANUGRAH ANWAR', 'email': 'rizki.anugrah.anwar91@kemenimipas.go.id'},
    {'nama': 'RIZKI ANUGRAH SARIPUDIN', 'email': 'rizki.anugrah.saripudin97@kemenimipas.go.id'},
    {'nama': 'RIZKI ANUGRAH', 'email': 'rizki.anugrah91@kemenimipas.go.id'},
    {'nama': 'RIZKI APRIANSYAH', 'email': 'rizki.apriansyah03@kemenimipas.go.id'},
    {'nama': 'RIZKI ARAFANTA SEBAYANG', 'email': 'rizki.arafanta.sebayang01@kemenimipas.go.id'},
    {'nama': 'RIZKI ARBAIN', 'email': 'rizki.arbain01@kemenimipas.go.id'},
    {'nama': 'RIZKI ARDIANSYAH', 'email': 'rizki.ardiansyah94@kemenimipas.go.id'},
    {'nama': 'RIZKI ARI KURNIAWAN RAMADHAN', 'email': 'rizki.ari.kurniawan.ramadhan97@kemenimipas.go.id'},
    {'nama': 'RIZKI ARIA PURNAMA', 'email': 'rizki.aria.purnama94@kemenimipas.go.id'},
    {'nama': 'RIZKI ARIANSYAH', 'email': 'rizki.ariansyah01@kemenimipas.go.id'},
    {'nama': 'RIZKI ARIES FERNANDO', 'email': 'rizki.aries.fernando84@kemenimipas.go.id'},
    {'nama': 'RIZKI ARIFIYANTO NUGRAHA', 'email': 'rizki.arifiyanto@kemenimipas.go.id'},
    {'nama': 'RIZKI ARIPUTRA', 'email': 'rizki.ariputra97@kemenimipas.go.id'},
    {'nama': 'RIZKI AULIA DWINANDA', 'email': 'rizki.aulia.dwinanda99@kemenimipas.go.id'},
    {'nama': 'RIZKI AULIA RACHADI', 'email': 'rizki.aulia.rachadi00@kemenimipas.go.id'},
    {'nama': 'RIZKI AULIYA', 'email': 'rizki.auliya01@kemenimipas.go.id'},
    {'nama': 'RIZKI AYU HANIFAH', 'email': 'rizki.ayu.hanifah96@kemenimipas.go.id'},
    {'nama': 'RIZKI AZIMA', 'email': 'rizki.azima93@kemenimipas.go.id'},
    {'nama': 'RIZKI BAGIO, S.Tr.Pas', 'email': 'rizki.bagio01@kemenimipas.go.id'},
    {'nama': 'RIZKI BUDIMAN', 'email': 'rizki.budiman@kemenimipas.go.id'},
    {'nama': 'RIZKI CAHYOSHA', 'email': 'rizki.cahyosha98@kemenimipas.go.id'},
    {'nama': 'RIZKI DHAFIN DHARMAWAN', 'email': 'rizki.dhafin.dharmawan98@kemenimipas.go.id'},
    {'nama': 'RIZKI DHARMAWAN SAPUTRA', 'email': 'rizki.dharmawan.saputra94@kemenimipas.go.id'},
    {'nama': 'RIZKI DIAN PURNAMA', 'email': 'rizki.dian@kemenimipas.go.id'},
    {'nama': 'RIZKI DWI HADIPUTRA', 'email': 'rizki.dwi.hadiputra87@kemenimipas.go.id'},
    {'nama': 'RIZKI DWI SETYAWAN', 'email': 'rizki.dwi.setyawan98@kemenimipas.go.id'},
    {'nama': 'RIZKI EFRAIM WOWILING', 'email': 'rizki.efraim.wowiling92@kemenimipas.go.id'},
    {'nama': 'RIZKI EKA AZHARI', 'email': 'rizki.eka.azhari03@kemenimipas.go.id'},
    {'nama': 'RIZKI EKA DARMAWAN', 'email': 'rizki.eka.darmawan92@kemenimipas.go.id'},
    {'nama': 'RIZKI ERDIANSYAH', 'email': 'rizki.erdiansyah01@kemenimipas.go.id'},
    {'nama': 'RIZKI FADILAH', 'email': 'rizki.fadilah92@kemenimipas.go.id'},
    {'nama': 'RIZKI FAJAR ERNANDA', 'email': 'rizki.fajar@kemenimipas.go.id'},
    {'nama': 'RIZKI FAJAR', 'email': 'rizki.fajar99@kemenimipas.go.id'},
    {'nama': 'RIZKI FAJRI', 'email': 'rizki.fajri@kemenimipas.go.id'},
    {'nama': 'RIZKI FANDU DWIKI', 'email': 'rizki.fandu@kemenimipas.go.id'},
    {'nama': 'M. RIZKI FAUJAN BAUD', 'email': 'rizki.faujan@kemenimipas.go.id'},
    {'nama': 'RIZKI FAUZI MAYENDRA', 'email': 'rizki.fauzi@kemenimipas.go.id'},
    {'nama': 'RIZKI FAUZIAH ARIEF', 'email': 'rizki.fauziah.arief01@kemenimipas.go.id'},
    {'nama': 'RIZKI FAUZY', 'email': 'rizki.fauzy96@kemenimipas.go.id'},
    {'nama': 'RIZKI FEBRIANDA', 'email': 'rizki.febrianda@kemenimipas.go.id'},
    {'nama': 'RIZKI FEBRIANTO MARTONO', 'email': 'rizki.febrianto@kemenimipas.go.id'},
    {'nama': 'RIZKI FEBRIYAN NUR HIDAYAT', 'email': 'rizki.febriyan.nur.hidayat99@kemenimipas.go.id'},
    {'nama': 'RIZKI FIRNANDA', 'email': 'rizki.firnanda95@kemenimipas.go.id'},
    {'nama': 'RIZKI FITRIYA', 'email': 'rizki.fitriya82@kemenimipas.go.id'},
    {'nama': 'RIZKI GUNAWAN PILIANG', 'email': 'rizki.gunawan.piliang85@kemenimipas.go.id'},
    {'nama': 'RIZKI HAMDANSYAH TANJUNG', 'email': 'rizki.hamdansyah@kemenimipas.go.id'},
    {'nama': 'RIZKI HARDIYAN', 'email': 'rizki.hardiyan97@kemenimipas.go.id'},
    {'nama': 'RIZKI HARI WIBOWO', 'email': 'rizki.hari.wibowo85@kemenimipas.go.id'},
    {'nama': 'RIZKI HARIS', 'email': 'rizki.haris@kemenimipas.go.id'},
    {'nama': 'RIZKI HARTO CATUR PUTRO, S.E', 'email': 'rizki.harto.catur.putro89@kemenimipas.go.id'},
    {'nama': 'RIZKI HARY PURNOMO', 'email': 'rizki.hary.purnomo94@kemenimipas.go.id'},
    {'nama': 'RIZKI HERDANU MULYADI', 'email': 'rizki.herdanu.mulyadi99@kemenimipas.go.id'},
    {'nama': 'RIZKI ILMANSYAH. L', 'email': 'rizki.ilmansyah.l01@kemenimipas.go.id'},
    {'nama': 'RIZKI IRSYADI', 'email': 'rizki.irsyadi95@kemenimipas.go.id'},
    {'nama': 'RIZKI JULIANA', 'email': 'rizki.juliana01@kemenimipas.go.id'},
    {'nama': 'RIZKI JURISMAN WERIPI', 'email': 'rizki.jurisman.weripi94@kemenimipas.go.id'},
    {'nama': 'RIZKI KAMELIA', 'email': 'rizki.kamelia@kemenimipas.go.id'},
    {'nama': 'RIZKI KAUTSAR PRAJOHAR', 'email': 'rizki.kautsar.prajohar98@kemenimipas.go.id'},
    {'nama': 'RIZKI KESUMA PUTRA', 'email': 'rizki.kesuma.putra88@kemenimipas.go.id'},
    {'nama': 'RIZKI KURNIA MARTA', 'email': 'rizki.kurnia.marta98@kemenimipas.go.id'},
    {'nama': 'RIZKI KURNIAWAN PUTRA HERNANDA', 'email': 'rizki.kurniawan.putra.hernanda99@kemenimipas.go.id'},
    {'nama': 'RIZKI KURNIAWAN', 'email': 'rizki.kurniawan2200@kemenimipas.go.id'},
    {'nama': 'RIZKI KURNIAWAN', 'email': 'rizki.kurniawan2700@kemenimipas.go.id'},
    {'nama': 'RIZKI KURNIAWAN, S.T', 'email': 'rizki.kurniawan90@kemenimipas.go.id'},
    {'nama': 'RIZKI LUTFIANTO', 'email': 'rizki.lutfianto91@kemenimipas.go.id'},
    {'nama': 'RIZKI M IQBAL DYAZ', 'email': 'rizki.m.iqbal.dyaz97@kemenimipas.go.id'},
    {'nama': 'RIZKI MARDHI ALWAN', 'email': 'rizki.mardhi@kemenimipas.go.id'},
    {'nama': 'RIZKI MAULANA Z', 'email': 'rizki.maulana.z00@kemenimipas.go.id'},
    {'nama': 'RIZKI MAULANA', 'email': 'rizki.maulana@kemenimipas.go.id'},
    {'nama': 'RIZKI MAULANA', 'email': 'rizki.maulana97@kemenimipas.go.id'},
    {'nama': 'RIZKI MAULI SIREGAR', 'email': 'Rizki.Mauli@kemenimipas.go.id'},
    {'nama': 'RIZKI MAULIADI', 'email': 'rizki.mauliadi@kemenimipas.go.id'},
    {'nama': 'RIZKI MUFLIH HAYAT', 'email': 'rizki.muflih.hayat05@kemenimipas.go.id'},
    {'nama': 'RIZKI MUHAMAD RIZAL', 'email': 'rizki.muhamad.rizal96@kemenimipas.go.id'},
    {'nama': 'RIZKI MULADI IRAWAN', 'email': 'rizki.muladi@kemenimipas.go.id'},
    {'nama': 'RIZKI MUNANDA', 'email': 'rizki.munanda96@kemenimipas.go.id'},
    {'nama': 'RIZKI MURYA PRATAMA', 'email': 'rizki.murya@kemenimipas.go.id'},
    {'nama': 'RIZKI MUSLIM SITEPU', 'email': 'rizki.muslim@kemenimipas.go.id'},
    {'nama': 'RIZKI NABILA YULIANTI', 'email': 'rizki.nabila.yulianti02@kemenimipas.go.id'},
    {'nama': 'RIZKI NANDA PUTRA WITHMAN', 'email': 'rizki.nanda@kemenimipas.go.id'},
    {'nama': 'RIZKI NOVIANI', 'email': 'rizki.noviani87@kemenimipas.go.id'},
    {'nama': 'RIZKI NUGRAHA', 'email': 'rizki.nugraha@kemenimipas.go.id'},
    {'nama': 'RIZKI NUR AFRIZAL', 'email': 'rizki.nur.afrizal97@kemenimipas.go.id'},
    {'nama': 'RIZKI NUR HIDAYAT', 'email': 'rizki.nur.hidayat98@kemenimipas.go.id'},
    {'nama': 'RIZKI NUR ISNANI', 'email': 'rizki.nur.isnani02@kemenimipas.go.id'},
    {'nama': 'RIZKI NURCHAER', 'email': 'rizki.nurchaer93@kemenimipas.go.id'},
    {'nama': 'RIZKI NURDIANSYAH', 'email': 'rizki.nurdiansyah92@kemenimipas.go.id'},
    {'nama': 'RIZKI NURHIMAWAN', 'email': 'rizki.nurhimawan99@kemenimipas.go.id'},
    {'nama': 'RIZKI NURLIANI', 'email': 'rizki.nurliani04@kemenimipas.go.id'},
    {'nama': 'RIZKI NURWIDIYANTO', 'email': 'rizki.nurwidiyanto91@kemenimipas.go.id'},
    {'nama': 'RIZKI OCTOVIANTA GINTING, S.E', 'email': 'rizki.octovianta@kemenimipas.go.id'},
    {'nama': 'RIZKI PADLI', 'email': 'rizki.padli89@kemenimipas.go.id'},
    {'nama': 'RIZKI PERDANA', 'email': 'rizki.perdana03@kemenimipas.go.id'},
    {'nama': 'RIZKI PERNANDA', 'email': 'rizki.pernanda95@kemenimipas.go.id'},
    {'nama': 'RIZKI PRABAYU UTAMI', 'email': 'rizki.prabayu.utami93@kemenimipas.go.id'},
    {'nama': 'RIZKI PRAMUDYA', 'email': 'rizki.pramudya02@kemenimipas.go.id'},
    {'nama': 'RIZKI PRASETYA', 'email': 'rizki.prasetya@kemenimipas.go.id'},
    {'nama': 'RIZKI PRATAMA, S.Tr.Im.', 'email': 'rizki.pratama99@kemenimipas.go.id'},
    {'nama': 'RIZKI PRAYOGA', 'email': 'rizki.prayoga98@kemenimipas.go.id'},
    {'nama': 'RIZKI PRIADIONO', 'email': 'rizki.priadiono90@kemenimipas.go.id'},
    {'nama': 'RIZKI PRIMANDA', 'email': 'rizki.primanda@kemenimipas.go.id'},
    {'nama': 'RIZKI PURNAMA', 'email': 'rizki.purnama96@kemenimipas.go.id'},
    {'nama': 'RIZKI PUTRA RAMADHAN', 'email': 'rizki.putra.ramadhan01@kemenimipas.go.id'},
    {'nama': 'RIZKI PUTRA', 'email': 'rizki.putra2392@kemenimipas.go.id'},
    {'nama': 'RIZKI PUTRA', 'email': 'rizki.putra2892@kemenimipas.go.id'},
    {'nama': 'RIZKI RAHMAT DANIARTO', 'email': 'rizki.rahmat.daniarto97@kemenimipas.go.id'},
    {'nama': 'RIZKI RAMAD SAPUTRA, S.Tr.Pas', 'email': 'rizki.ramad.saputra00@kemenimipas.go.id'},
    {'nama': 'RIZKI RAMADHAN', 'email': 'rizki.ramadhan@kemenimipas.go.id'},
    {'nama': 'RIZKI RAMADHAN', 'email': 'rizki.ramadhan94@kemenimipas.go.id'},
    {'nama': 'RIZKI RAMADHAN', 'email': 'rizki.ramadhan98@kemenimipas.go.id'},
    {'nama': 'RIZKI RAMDAN FITRONI', 'email': 'rizki.ramdan.fitroni05@kemenimipas.go.id'},
    {'nama': 'RIZKI RELIN SUDTRA YOGI', 'email': 'rizki.relin.sudtra.yogi99@kemenimipas.go.id'},
    {'nama': 'RIZKI RESTIYANI', 'email': 'rizki.restiyani98@kemenimipas.go.id'},
    {'nama': 'RIZKI RIDWAN LIHAWA', 'email': 'rizki.ridwan@kemenimipas.go.id'},
    {'nama': 'RIZKI RIDWAN RAMDANI', 'email': 'rizki.ridwan921@kemenimipas.go.id'},
    {'nama': 'RIZKI RINALDI', 'email': 'rizki.rinaldi06@kemenimipas.go.id'},
    {'nama': 'RIZKI RIZALDI FADHILLAH', 'email': 'rizki.rizaldi.fadhillah97@kemenimipas.go.id'},
    {'nama': 'RIZKI ROSSA TRIHANDINI', 'email': 'rizki.rossa.trihandini00@kemenimipas.go.id'},
    {'nama': 'RIZKI SAPUTRA', 'email': 'rizki.saputra93@kemenimipas.go.id'},
    {'nama': 'RIZKI SEPDIANA', 'email': 'rizki.sepdiana98@kemenimipas.go.id'},
    {'nama': 'RIZKI SETIAJI MUTAQIN', 'email': 'Rizki.setiaji@kemenimipas.go.id'},
    {'nama': 'RIZKI SETYA BUDIARTO', 'email': 'rizki.setya.budiarto98@kemenimipas.go.id'},
    {'nama': 'RIZKI SHAPUTRA', 'email': 'rizki.shaputra97@kemenimipas.go.id'},
    {'nama': 'RIZKI SRI HANDAYANI', 'email': 'rizki.sri@kemenimipas.go.id'},
    {'nama': 'RIZKI SURYA DARMA', 'email': 'rizki.surya.darma05@kemenimipas.go.id'},
    {'nama': 'RIZKI SURYA DHARMA', 'email': 'rizki.surya@kemenimipas.go.id'},
    {'nama': 'RIZKI SUSANTI', 'email': 'rizki.susanti@kemenimipas.go.id'},
    {'nama': 'RIZKI SYAEFUL AMIN', 'email': 'rizki.syaeful.amin02@kemenimipas.go.id'},
    {'nama': 'RIZKI SYAHPUTRA', 'email': 'rizki.syahputra97@kemenimipas.go.id'},
    {'nama': 'RIZKI TARMUZI', 'email': 'rizki.tarmuzi@kemenimipas.go.id'},
    {'nama': 'RIZKI TAWAQAL', 'email': 'rizki.tawaqal94@kemenimipas.go.id'},
    {'nama': 'RIZKI TIRAJI', 'email': 'rizki.tiraji@kemenimipas.go.id'},
    {'nama': 'RIZKI TIRTA RAMDANI', 'email': 'rizki.tirta.ramdani98@kemenimipas.go.id'},
    {'nama': 'RIZKI TRIBOWO HUMARDANI', 'email': 'rizki.tribowo.humardani95@kemenimipas.go.id'},
    {'nama': 'RIZKI WAHYUDI', 'email': 'rizki.wahyudi@kemenimipas.go.id'},
    {'nama': 'RIZKI WAHYUDI', 'email': 'rizki.wahyudi77@kemenimipas.go.id'},
    {'nama': 'RIZKI WAHYUDI', 'email': 'rizki.wahyudi86@kemenimipas.go.id'},
    {'nama': 'RIZKI WIBOWO', 'email': 'rizki.wibowo@kemenimipas.go.id'},
    {'nama': 'RIZKI WIBOWO, S.H.', 'email': 'rizki.wibowo943@kemenimipas.go.id'},
    {'nama': 'RIZKI WIDHI KUSUMA', 'email': 'rizki.widhi.kusuma02@kemenimipas.go.id'},
    {'nama': 'RIZKI WIDI PRASONGKO', 'email': 'rizki.widi.prasongko89@kemenimipas.go.id'},
    {'nama': 'RIZKI WIJAYA HASIBUAN', 'email': 'rizki.wijaya@kemenimipas.go.id'},
    {'nama': 'RIZKI YOANKARITA, S.E.', 'email': 'rizki.yoankarita88@kemenimipas.go.id'},
    {'nama': 'RIZKI YOGA PRIAMBODO', 'email': 'rizki.yoga@kemenimipas.go.id'},
    {'nama': 'RIZKI YUDHA MAULANA', 'email': 'rizki.yudha.maulana85@kemenimipas.go.id'},
    {'nama': 'RIZKI YUDHA SATRIA', 'email': 'rizki.yudha.satria04@kemenimipas.go.id'},
    {'nama': 'RIZKI YUDHAPUTRA', 'email': 'rizki.yudhaputra95@kemenimipas.go.id'},
    {'nama': 'RIZKI YULISMA SARI', 'email': 'rizki.yulisma.sari84@kemenimipas.go.id'},
    {'nama': 'RIZKI. Z', 'email': 'rizki.z97@kemenimipas.go.id'},
    {'nama': 'RIZKI ZAKI FADILAH', 'email': 'rizki.zaki.fadilah04@kemenimipas.go.id'},
    {'nama': 'RIZKI ZULHAJJI RITONGA', 'email': 'rizki.zulhajji@kemenimipas.go.id'},
    {'nama': 'RIZKIA AMELIA', 'email': 'rizkia.amelia@kemenimipas.go.id'},
    {'nama': 'RIZKIA HANNA AMALIA', 'email': 'rizkia.hannaamalia@kemenimipas.go.id'},
    {'nama': 'RIZKIA IMANUELA BR. SIAHAAN', 'email': 'rizkia.imanuela.br.siahaan03@kemenimipas.go.id'},
    {'nama': 'RIZKIA LESTARI', 'email': 'rizkia.lestari@kemenimipas.go.id'},
    {'nama': 'RIZKIE REZA FADILLA', 'email': 'rizkie.reza.fadilla98@kemenimipas.go.id'},
    {'nama': 'RIZKIE VANDAPOTAN SINAGA', 'email': 'rizkie.vandapotan@kemenimipas.go.id'},
    {'nama': 'RIZKI KARIMA VITO CHRISMASTANTO', 'email': 'rizkikarima.vitochrismastanto@kemenimipas.go.id'},
    {'nama': 'RIZKI NALDI', 'email': 'rizkinaldi@kemenimipas.go.id'},
    {'nama': 'RIZKITA WILANGGA', 'email': 'rizkita.wilangga98@kemenimipas.go.id'},
    {'nama': 'RIZKIYANTO HATTA, S.H', 'email': 'rizkiyanto.hatta@kemenimipas.go.id'},
    {'nama': 'RIZKIYANTO', 'email': 'rizkiyanto@kemenimipas.go.id'},
    {'nama': 'RIZKUL AKSAR ADIWINATA', 'email': 'rizkul.aksar.adiwinata01@kemenimipas.go.id'},
    {'nama': 'RIZKY ABADI PUTRA', 'email': 'rizky.abadi@kemenimipas.go.id'},
    {'nama': 'RIZKY ABDOL FATONI', 'email': 'rizky.abdol@kemenimipas.go.id'},
    {'nama': 'RIZKY ADI SYAHPUTRA', 'email': 'rizky.adi.syahputra99@kemenimipas.go.id'},
    {'nama': 'RIZKY ADISUKMA PUTRANTO', 'email': 'rizky.adisukma.putranto02@kemenimipas.go.id'},
    {'nama': 'RIZKY ADRIAN NAKALELO', 'email': 'rizky.adrian.nakalelo91@kemenimipas.go.id'},
    {'nama': 'RIZKY ADRIANSYAH', 'email': 'rizky.adriansyah01@kemenimipas.go.id'},
    {'nama': 'RIZKY AGUNG PRASETYO', 'email': 'rizky.agung.prasetyo04@kemenimipas.go.id'},
    {'nama': 'RIZKY AGUNG SYAHPUTRA', 'email': 'rizky.agung.syahputra01@kemenimipas.go.id'},
    {'nama': 'RIZKY AJI SETIAWAN', 'email': 'rizky.aji@kemenimipas.go.id'},
    {'nama': 'RIZKY ALAMSYAH', 'email': 'rizky.alamsyah91@kemenimipas.go.id'},
    {'nama': 'RIZKY ALDI', 'email': 'rizky.aldi98@kemenimipas.go.id'},
    {'nama': 'RIZKY ALDIANSYAH', 'email': 'rizky.aldiansyah93@kemenimipas.go.id'},
    {'nama': 'RIZKY ALFHIATNA', 'email': 'rizky.alfhiatna@kemenimipas.go.id'},
    {'nama': 'RIZKY ALFIAN DWI PUTRA DUWILA', 'email': 'rizky.alfian.dwi.putra.duwila03@kemenimipas.go.id'},
    {'nama': 'RIZKY ALVIN PRATAMA', 'email': 'rizky.alvin.pratama97@kemenimipas.go.id'},
    {'nama': 'RIZKY AMALIA SHOLIHA, S.Psi.', 'email': 'rizky.amalia.sholiha99@kemenimipas.go.id'},
    {'nama': 'RIZKY AMALIA', 'email': 'rizky.amalia87@kemenimipas.go.id'},
    {'nama': 'RIZKY AMALY HIDAYAT', 'email': 'rizky.amaly.hidayat96@kemenimipas.go.id'},
    {'nama': 'RIZKY AMIENUHDIN,S.E', 'email': 'rizky.amienuhdin@kemenimipas.go.id'},
    {'nama': 'RIZKY ANALIA PUTRI NINGRUM', 'email': 'rizky.analia.putri.ningrum86@kemenimipas.go.id'},
    {'nama': 'RIZKY ANANDA CAHAYA PUTRA', 'email': 'rizky.ananda.cahaya.putra01@kemenimipas.go.id'},
    {'nama': 'RIZKY ANANDA', 'email': 'rizky.ananda99@kemenimipas.go.id'},
    {'nama': 'RIZKY ANDARUJATI , S.Tr.Im', 'email': 'rizky.andarujati96@kemenimipas.go.id'},
    {'nama': 'RIZKY ANDRIAN', 'email': 'rizky.andrian03@kemenimipas.go.id'},
    {'nama': 'RIZKY ANDRIANSYAH', 'email': 'rizky.andriansyah95@kemenimipas.go.id'},
    {'nama': 'RIZKY APRILIA WIBISONO', 'email': 'rizky.aprilia.wibisono99@kemenimipas.go.id'},
    {'nama': 'RIZKY ARDI GUNAWAN', 'email': 'rizky.ardi.gunawan96@kemenimipas.go.id'},
    {'nama': 'RIZKY ARDI PUTRA', 'email': 'rizky.ardi.putra97@kemenimipas.go.id'},
    {'nama': 'RIZKY ARDIANSYAH', 'email': 'rizky.ardiansyah99@kemenimipas.go.id'},
    {'nama': 'RIZKY ARDIWIJAYA', 'email': 'rizky.ardiwijaya98@kemenimipas.go.id'},
    {'nama': 'RIZKY ARIYANTO', 'email': 'rizky.ariyanto04@kemenimipas.go.id'},
    {'nama': 'RIZKY ARYA PRASETIYA', 'email': 'rizky.arya@kemenimipas.go.id'},
    {'nama': 'RIZKY ARYAPUTRA', 'email': 'rizky.aryaputra01@kemenimipas.go.id'},
    {'nama': 'RIZKY AULIA', 'email': 'rizky.aulia03@kemenimipas.go.id'},
    {'nama': 'RIZKY AULIA BASRI', 'email': 'rizky.aulia883@kemenimipas.go.id'},
    {'nama': 'RIZKY AZI SYAHPUTRA', 'email': 'rizky.azi.syahputra00@kemenimipas.go.id'},
    {'nama': 'RIZKY AZWARI', 'email': 'rizky.azwari@kemenimipas.go.id'},
    {'nama': 'RIZKY B. ANGKUNA, S.Tr.Pas.', 'email': 'rizky.b.angkuna98@kemenimipas.go.id'},
    {'nama': 'RIZKY BACHROWI ASTARI', 'email': 'rizky.bachrowi.astari01@kemenimipas.go.id'},
    {'nama': 'RIZKY BAGINDA PARHIMPUNAN SIREGAR', 'email': 'rizky.baginda.parhimpunan.siregar92@kemenimipas.go.id'},
    {'nama': 'RIZKY BAGUS FATHUR RACHMAN', 'email': 'rizky.bagus.fathur.rachman96@kemenimipas.go.id'},
    {'nama': 'RIZKY BAGUS PRATAMA', 'email': 'rizky.bagus.pratama04@kemenimipas.go.id'},
    {'nama': 'RIZKY BALUNTU KAKANIO', 'email': 'rizky.baluntu.kakanio00@kemenimipas.go.id'},
    {'nama': 'RIZKY BRILIANTO', 'email': 'rizky.brilianto05@kemenimipas.go.id'},
    {'nama': 'RIZKY CAHYA WULANDARI', 'email': 'rizky.cahya.wulandari93@kemenimipas.go.id'},
    {'nama': 'RIZKY CHANDRA WIGUNA', 'email': 'rizky.chandra.wiguna98@kemenimipas.go.id'},
    {'nama': 'RIZKY DANNY SETYAWAN', 'email': 'rizky.danny.setyawan96@kemenimipas.go.id'},
    {'nama': 'RIZKY DARMAWAN  S', 'email': 'rizky.darmawan.s94@kemenimipas.go.id'},
    {'nama': 'RIZKY DARMAWANSYAH', 'email': 'rizky.darmawansyah93@kemenimipas.go.id'},
    {'nama': 'RIZKY DAROJAT', 'email': 'rizky.darojat@kemenimipas.go.id'},
    {'nama': 'RIZKY DHIPA ANGGATRI', 'email': 'rizky.dhipa.anggatri85@kemenimipas.go.id'},
    {'nama': 'RIZKY DIKARA PRIATAMA', 'email': 'rizky.dikara.priatama99@kemenimipas.go.id'},
    {'nama': 'RIZKY DINDA MAULIDYA', 'email': 'rizky.dinda.maulidya99@kemenimipas.go.id'},
    {'nama': 'RIZKY DLIYAUL HAQQI', 'email': 'rizky.dliyaul@kemenimipas.go.id'},
    {'nama': 'RIZKY DWI KURNIAWAN', 'email': 'rizky.dwi.kurniawan05@kemenimipas.go.id'},
    {'nama': 'RIZKY DWI NUGRAHA', 'email': 'rizky.dwi.nugraha01@kemenimipas.go.id'},
    {'nama': 'RIZKY DWI NURDIANSYAH', 'email': 'rizky.dwi.nurdiansyah94@kemenimipas.go.id'},
    {'nama': 'RIZKY DWI HARTANTO', 'email': 'rizky.dwi@kemenimipas.go.id'},
    {'nama': 'RIZKY DWILIYANTO ALIMIN', 'email': 'rizky.dwiliyanto.alimin95@kemenimipas.go.id'},
    {'nama': 'RIZKY EKO HIDAYATULLAH', 'email': 'rizky.eko.hidayatullah01@kemenimipas.go.id'},
    {'nama': 'RIZKY EKO AGUS CAHYONO', 'email': 'rizky.eko@kemenimipas.go.id'},
    {'nama': 'RIZKY ERYANTO ISKANDAR', 'email': 'rizky.eryanto.iskandar97@kemenimipas.go.id'},
    {'nama': 'RIZKY FADHILLAH', 'email': 'rizky.fadhillah98@kemenimipas.go.id'},
    {'nama': 'RIZKY FADILA', 'email': 'rizky.fadila98@kemenimipas.go.id'},
    {'nama': 'RIZKY FADILLAH', 'email': 'rizky.fadillah@kemenimipas.go.id'},
    {'nama': 'RIZKY FADLI', 'email': 'rizky.fadli99@kemenimipas.go.id'},
    {'nama': 'RIZKY FAJAR ADEPUTRA', 'email': 'rizky.fajar@kemenimipas.go.id'},
    {'nama': 'RIZKY FEBRI NURZANTI, A.Md', 'email': 'rizky.febri@kemenimipas.go.id'},
    {'nama': 'RIZKY FIRMANSYAH', 'email': 'rizky.firmansyah01@kemenimipas.go.id'},
    {'nama': 'RIZKY FIRMANSYAH', 'email': 'rizky.firmansyah98@kemenimipas.go.id'},
    {'nama': 'RIZKY FRANS SYAHPUTRA', 'email': 'rizky.frans@kemenimipas.go.id'},
    {'nama': 'RIZKY GISTIYAN, S.E', 'email': 'rizky.gistiyan@kemenimipas.go.id'},
    {'nama': 'RIZKY GUNAWAN', 'email': 'rizky.gunawan96@kemenimipas.go.id'},
    {'nama': '-. RIZKY HABIB HASIBUAN, -', 'email': 'rizky.habib.hasibuan03@kemenimipas.go.id'},
    {'nama': 'RIZKY HABIBI', 'email': 'rizky.habibi06@kemenimipas.go.id'},
    {'nama': 'RIZKY HAMONANGAN SIMANJUNTAK', 'email': 'rizky.hamonangan.simanjuntak97@kemenimipas.go.id'},
    {'nama': 'RIZKY HAMONANGAN RUMAPEA', 'email': 'rizky.hamonangan@kemenimipas.go.id'},
    {'nama': 'RIZKY HAPRI SEPTIAWAN', 'email': 'rizky.hapri.septiawan01@kemenimipas.go.id'},
    {'nama': 'RIZKY HARDIANSYAH', 'email': 'rizky.hardiansyah98@kemenimipas.go.id'},
    {'nama': 'RIZKY HERVIANI', 'email': 'rizky.herviani92@kemenimipas.go.id'},
    {'nama': 'RIZKY HIDAYAT', 'email': 'rizky.hidayat03@kemenimipas.go.id'},
    {'nama': 'RIZKY IKHSAN MULIYAWAN', 'email': 'rizky.ikhsan.muliyawan87@kemenimipas.go.id'},
    {'nama': 'RIZKY ILHAM FATAHILLAH', 'email': 'rizky.ilham.fatahillah02@kemenimipas.go.id'},
    {'nama': 'RIZKY JAKA SEPUTRA THALIB', 'email': 'rizky.jaka.seputra.thalib91@kemenimipas.go.id'},
    {'nama': 'RIZKY JULFIAN MAHFUD', 'email': 'rizky.julfian.mahfud87@kemenimipas.go.id'},
    {'nama': 'RIZKY JUNI ALDINO', 'email': 'rizky.juni@kemenimipas.go.id'},
    {'nama': 'RIZKY KHOIRUN NAWALI', 'email': 'rizky.khoirun.nawali02@kemenimipas.go.id'},
    {'nama': 'RIZKY KURNIA PUTRI', 'email': 'rizky.kurnia.putri96@kemenimipas.go.id'},
    {'nama': 'RIZKY KURNIAWAN. S', 'email': 'rizky.kurniawan.s94@kemenimipas.go.id'},
    {'nama': 'RIZKY KURNIAWAN', 'email': 'rizky.kurniawan95@kemenimipas.go.id'},
    {'nama': 'RIZKY KURNIAWAN', 'email': 'rizky.kurniawan97@kemenimipas.go.id'},
    {'nama': 'RIZKY KUSWURYONO', 'email': 'rizky.kuswuryono82@kemenimipas.go.id'},
    {'nama': 'RIZKY LESMANA', 'email': 'rizky.lesmana@kemenimipas.go.id'},
    {'nama': 'RIZKY MAHENDRA', 'email': 'rizky.mahendra92@kemenimipas.go.id'},
    {'nama': 'RIZKY MARISSA', 'email': 'rizky.marissa91@kemenimipas.go.id'},
    {'nama': 'RIZKY MARTIN', 'email': 'rizky.martin@kemenimipas.go.id'},
    {'nama': 'RIZKY MAULANA', 'email': 'rizky.maulana@kemenimipas.go.id'},
    {'nama': 'RIZKY MAULANA AGUSNI', 'email': 'rizky.maulana953@kemenimipas.go.id'},
    {'nama': 'RIZKY MAULANA PUTERA', 'email': 'rizky.maulana986@kemenimipas.go.id'},
    {'nama': 'RIZKY MEILIANA PUTRI', 'email': 'rizky.meiliana.putri02@kemenimipas.go.id'},
    {'nama': 'RIZKY MILENIA', 'email': 'rizky.milenia00@kemenimipas.go.id'},
    {'nama': 'RIZKY MOHAMMAD ZEIN', 'email': 'rizky.mohammad.zein94@kemenimipas.go.id'},
    {'nama': 'RIZKY MUHAMMAD IRSYAAD', 'email': 'rizky.muhammad.irsyaad01@kemenimipas.go.id'},
    {'nama': 'RIZKY MUHARMAN', 'email': 'rizky.muharman98@kemenimipas.go.id'},
    {'nama': 'RIZKY MUNANDAR', 'email': 'rizky.munandar94@kemenimipas.go.id'},
    {'nama': 'RIZKY MURSALIN MALIK', 'email': 'rizky.mursalin.malik92@kemenimipas.go.id'},
    {'nama': 'RIZKY MUSTAQIM ODE', 'email': 'rizky.mustaqim.ode97@kemenimipas.go.id'},
    {'nama': 'RIZKY NADYA FATMA', 'email': 'rizky.nadya.fatma98@kemenimipas.go.id'},
    {'nama': 'RIZKY NANDA PERDANA', 'email': 'rizky.nanda.perdana92@kemenimipas.go.id'},
    {'nama': 'RIZKY NANDA', 'email': 'rizky.nanda@kemenimipas.go.id'},
    {'nama': 'RIZKY NOFRIYANSYAH RUSLAN', 'email': 'rizky.nofriyansyah.ruslan05@kemenimipas.go.id'},
    {'nama': 'RIZKY NOOR JAYA PRAMUDITYA', 'email': 'rizky.noor.jaya.pramuditya02@kemenimipas.go.id'},
    {'nama': 'RIZKY NOOR KHADAFY', 'email': 'rizky.noor.khadafy86@kemenimipas.go.id'},
    {'nama': 'RIZKY NOOR MUJIONO PUTRO', 'email': 'rizky.noor.mujiono.putro95@kemenimipas.go.id'},
    {'nama': 'RIZKY NOPASA', 'email': 'rizky.nopasa@kemenimipas.go.id'},
    {'nama': 'RIZKY NOVAL PRATAMA', 'email': 'rizky.noval.pratama04@kemenimipas.go.id'},
    {'nama': 'RIZKY NUR HARYANI', 'email': 'rizky.nur.haryani88@kemenimipas.go.id'},
    {'nama': 'RIZKY NUR MUHAMMAD', 'email': 'rizky.nur.muhammad01@kemenimipas.go.id'},
    {'nama': 'RIZKY NUR ADIYAT', 'email': 'Rizky.Nur78@kemenimipas.go.id'},
    {'nama': 'RIZKY OKTAVIANA', 'email': 'rizky.oktaviana96@kemenimipas.go.id'},
    {'nama': 'RIZKY PAMULA ARDIANA', 'email': 'rizky.pamula.ardiana94@kemenimipas.go.id'},
    {'nama': 'RIZKY PARAMITA BASAE', 'email': 'rizky.paramita@kemenimipas.go.id'},
    {'nama': 'RIZKY PERDANA', 'email': 'rizky.perdana99@kemenimipas.go.id'},
    {'nama': 'RIZKY PRADANA PUTRA', 'email': 'rizky.pradana.putra03@kemenimipas.go.id'},
    {'nama': 'RIZKY PRATAMA', 'email': 'rizky.pratama02@kemenimipas.go.id'},
    {'nama': 'RIZKY PRATAMA', 'email': 'rizky.pratama1392@kemenimipas.go.id'},
    {'nama': 'RIZKY PRATAMA', 'email': 'rizky.pratama2492@kemenimipas.go.id'},
    {'nama': 'RIZKY PRATAMA, S.Tr.Im.', 'email': 'rizky.pratama99@kemenimipas.go.id'},
    {'nama': 'RIZKY PRIYAPRATAMA', 'email': 'rizky.priyapratama82@kemenimipas.go.id'},
    {'nama': 'RIZKY PUTRA GUSFAR', 'email': 'rizky.putra.gusfar01@kemenimipas.go.id'},
    {'nama': 'RIZKY PUTRA PRIYATNA', 'email': 'rizky.putra.priyatna04@kemenimipas.go.id'},
    {'nama': 'RIZKY PUTRA SEPTIANTO', 'email': 'rizky.putra.septianto98@kemenimipas.go.id'},
    {'nama': 'RIZKY R. HUTAJULU', 'email': 'rizky.r.hutajulu97@kemenimipas.go.id'},
    {'nama': 'RIZKY R. RUBINGIN', 'email': 'rizky.r.rubingin98@kemenimipas.go.id'},
    {'nama': 'RIZKY RACHMAT RAMADHAN', 'email': 'rizky.rachmat@kemenimipas.go.id'},
    {'nama': 'RIZKY RAFSHANJANI', 'email': 'rizky.rafshanjani@kemenimipas.go.id'},
    {'nama': 'RIZKY RAHAYU SETYAWAN', 'email': 'rizky.rahayusetyawan@kemenimipas.go.id'},
    {'nama': 'RIZKY RAHMADDI', 'email': 'rizky.rahmaddi97@kemenimipas.go.id'},
    {'nama': 'RIZKY RAMADHAN ADI WIJAYA, S.Tr.Pas', 'email': 'rizky.ramadhan.adi.wijaya99@kemenimipas.go.id'},
    {'nama': 'RIZKY RAMADHAN', 'email': 'rizky.ramadhan@kemenimipas.go.id'},
    {'nama': 'RIZKY RAMADHAN', 'email': 'rizky.ramadhan001@kemenimipas.go.id'},
    {'nama': 'RIZKY RAMADHAN', 'email': 'rizky.ramadhan01@kemenimipas.go.id'},
    {'nama': 'RIZKY RAMADHAN', 'email': 'rizky.ramadhan94@kemenimipas.go.id'},
    {'nama': 'RIZKY RAMADHAN', 'email': 'rizky.ramadhan98@kemenimipas.go.id'},
    {'nama': 'RIZKY RAMADHANI', 'email': 'rizky.ramadhani@kemenimipas.go.id'},
    {'nama': 'RIZKY RAMADHANI, S.IP', 'email': 'rizky.ramadhani92@kemenimipas.go.id'},
    {'nama': 'RIZKY RAMADHANSYAH', 'email': 'rizky.ramadhansyah98@kemenimipas.go.id'},
    {'nama': 'RIZKY RIANGGONO', 'email': 'rizky.rianggono92@kemenimipas.go.id'},
    {'nama': 'RIZKY RIANTO', 'email': 'rizky.rianto02@kemenimipas.go.id'},
    {'nama': 'RIZKY RIANTO', 'email': 'rizky.rianto03@kemenimipas.go.id'},
    {'nama': 'RIZKY RICHARD TAKATELIDE', 'email': 'rizky.richard.takatelide90@kemenimipas.go.id'},
    {'nama': 'RIZKY RINALDY', 'email': 'rizky.rinaldy00@kemenimipas.go.id'},
    {'nama': 'RIZKY RIVANTO BUAMONA', 'email': 'rizky.rivanto.buamona96@kemenimipas.go.id'},
    {'nama': 'RIZKY SARO PUTRA SARAGIH', 'email': 'rizky.saro@kemenimipas.go.id'},
    {'nama': 'RIZKY SAULUS NGANGGU DIMA', 'email': 'rizky.saulus@kemenimipas.go.id'},
    {'nama': 'RIZKY SEPTIN WARDANI', 'email': 'rizky.septin@kemenimipas.go.id'},
    {'nama': 'RIZKY SETIADI', 'email': 'rizky.setiadi@kemenimipas.go.id'},
    {'nama': 'RIZKY SETIAWAN', 'email': 'rizky.setiawan02@kemenimipas.go.id'},
    {'nama': 'RIZKY SETYO PRABOWO', 'email': 'rizky.setyo.prabowo94@kemenimipas.go.id'},
    {'nama': 'RIZKY SETYOADJI', 'email': 'rizky.setyoadji97@kemenimipas.go.id'},
    {'nama': 'RIZKY SUBAGYA', 'email': 'rizky.subagya@kemenimipas.go.id'},
    {'nama': 'RIZKY SYAHID JAMALUDIN', 'email': 'rizky.syahid@kemenimipas.go.id'},
    {'nama': 'RIZKY TEGUH PUTRA MENDROFA', 'email': 'rizky.teguh.putra.mendrofa05@kemenimipas.go.id'},
    {'nama': 'RIZKY TRI IRJAYANTO', 'email': 'rizky.tri.irjayanto93@kemenimipas.go.id'},
    {'nama': 'RIZKY TRI NUGROHO', 'email': 'rizky.tri.nugroho96@kemenimipas.go.id'},
    {'nama': 'RIZKY UTARI', 'email': 'Rizky.Utari@kemenimipas.go.id'},
    {'nama': 'RIZKY UTIA', 'email': 'rizky.utia00@kemenimipas.go.id'},
    {'nama': 'RIZKY VIZANO', 'email': 'rizky.vizano98@kemenimipas.go.id'},
    {'nama': 'RIZKY WAHYU AMALINDA', 'email': 'rizky.wahyu.amalinda01@kemenimipas.go.id'},
    {'nama': 'RIZKY WAHYU OKTOVIAN', 'email': 'rizky.wahyu.oktovian99@kemenimipas.go.id'},
    {'nama': 'RIZKY WAHYU RAMADHAN', 'email': 'rizky.wahyu.ramadhan96@kemenimipas.go.id'},
    {'nama': 'RIZKY WAHYU SAPUTRA', 'email': 'rizky.wahyu.saputra90@kemenimipas.go.id'},
    {'nama': 'RIZKY WAHYU SYAHPUTRA', 'email': 'rizky.wahyu.syahputra94@kemenimipas.go.id'},
    {'nama': 'RIZKY WAHYUDI', 'email': 'rizky.wahyudi91@kemenimipas.go.id'},
    {'nama': 'RIZKY WIDI SAPUTRA', 'email': 'rizky.widi@kemenimipas.go.id'},
    {'nama': 'RIZKY WISNU PRAYUDA NUSANTARA', 'email': 'rizky.wisnu.prayuda.nusantara95@kemenimipas.go.id'},
    {'nama': 'RIZKY YANSYAH', 'email': 'rizky.yansyah89@kemenimipas.go.id'},
    {'nama': 'RIZKY YANTA MERAHABIA', 'email': 'rizky.yanta@kemenimipas.go.id'},
    {'nama': 'RIZKY YUDHAIKAWIRA', 'email': 'rizky.yudhaikawira@kemenimipas.go.id'},
    {'nama': 'RIZKY YUSUF PRAMADEVA', 'email': 'rizky.yusuf.pramadeva03@kemenimipas.go.id'},
    {'nama': 'RIZKY ZATHA MAHENDRA TURRU', 'email': 'rizky.zatha@kemenimipas.go.id'},
    {'nama': 'RIZKY ZUHRI WIYADI', 'email': 'rizky.zuhri.wiyadi02@kemenimipas.go.id'},
    {'nama': 'RIZKY ZULDI SAPUTRA', 'email': 'rizky.zuldi.saputra93@kemenimipas.go.id'},
    {'nama': 'RIZKYANA KURNIAWATI, A.Md.Kep.', 'email': 'rizkyana.kurniawati98@kemenimipas.go.id'},
    {'nama': 'RIZKYNANDA BUSMA PRATAMA', 'email': 'rizkynanda.busma@kemenimipas.go.id'},
    {'nama': 'RIZKYNANDA FINHARTANTO', 'email': 'rizkynanda.finhartanto02@kemenimipas.go.id'},
    {'nama': 'RIZKYTA SEPTIANTI HARAHAP', 'email': 'rizkyta.septianti@kemenimipas.go.id'},
    {'nama': 'RIZKY WAHYU RAMADANI', 'email': 'rizkywahyu.ramadani@kemenimipas.go.id'},
    {'nama': 'RIZKYZATUNKY FIERDINAND OHEI', 'email': 'rizkyzatunky.fierdinand.ohei96@kemenimipas.go.id'},
    {'nama': 'RIZMAWAN WIDI WIRANATA', 'email': 'rizmawan.widi.wiranata97@kemenimipas.go.id'},
    {'nama': 'RIZNA WAHYUNINGTYAS', 'email': 'rizna.wahyuningtyas91@kemenimipas.go.id'},
    {'nama': 'RIZONA', 'email': 'rizona92@kemenimipas.go.id'},
    {'nama': 'RIZQA MAULIDA FITRI', 'email': 'rizqa.maulida.fitri90@kemenimipas.go.id'},
    {'nama': 'RIZQAN SYAHRU RAMADHAN', 'email': 'rizqan.syahru.ramadhan00@kemenimipas.go.id'},
    {'nama': 'Rizqan', 'email': 'rizqan84@kemenimipas.go.id'},
    {'nama': 'RIZQI AGUNG NUGROHO', 'email': 'rizqi.agung.nugroho95@kemenimipas.go.id'},
    {'nama': 'RIZQI AGUNG SRIWIJAYA', 'email': 'rizqi.agung.sriwijaya00@kemenimipas.go.id'},
    {'nama': 'RIZQI AMANDA', 'email': 'rizqi.amanda01@kemenimipas.go.id'},
    {'nama': 'RIZQI ARIF PRADANA', 'email': 'rizqi.arif.pradana95@kemenimipas.go.id'},
    {'nama': 'RIZQI AYU NOVARA', 'email': 'rizqi.ayu@kemenimipas.go.id'},
    {'nama': 'RIZQI DESLIANDA DAMRIS', 'email': 'rizqi.deslianda.damris03@kemenimipas.go.id'},
    {'nama': 'RIZQI GANIS ASHARI, S.I.Kom., M.I.Kom', 'email': 'rizqi.ganisashari@kemenimipas.go.id'},
    {'nama': 'RIZQI HIDAYAH', 'email': 'rizqi.hidayah83@kemenimipas.go.id'},
    {'nama': 'RIZQI IRVANSYAH PRATAMA', 'email': 'rizqi.irvansyah.pratama98@kemenimipas.go.id'},
    {'nama': 'RIZQI JAPANDA RISTIAN', 'email': 'rizqi.japanda.ristian05@kemenimipas.go.id'},
    {'nama': 'RIZQI MAULANA', 'email': 'rizqi.maulana02@kemenimipas.go.id'},
    {'nama': 'RIZQI MELY TRIMIYATI', 'email': 'rizqi.mely.trimiyati99@kemenimipas.go.id'},
    {'nama': 'RIZQI NAUFAL', 'email': 'rizqi.naufal98@kemenimipas.go.id'},
    {'nama': 'RIZQI NIKMATULLAH', 'email': 'rizqi.nikmatullah97@kemenimipas.go.id'},
    {'nama': 'RIZQI NUGROHO', 'email': 'rizqi.nugroho99@kemenimipas.go.id'},
    {'nama': 'RIZQI OCTARIANSYAH', 'email': 'rizqi.octariansyah03@kemenimipas.go.id'},
    {'nama': 'RIZQI PUTRA SANDIKA', 'email': 'rizqi.putra.sandika92@kemenimipas.go.id'},
    {'nama': 'RIZQI RAHMATILLAH', 'email': 'rizqi.rahmatillah@kemenimipas.go.id'},
    {'nama': 'RIZQI RAMADHAN', 'email': 'rizqi.ramadhan99@kemenimipas.go.id'},
    {'nama': 'RIZQI RIDHO ATMADJA', 'email': 'rizqi.ridho.atmadja98@kemenimipas.go.id'},
    {'nama': 'RIZQI SYARAFI', 'email': 'rizqi.syarafi@kemenimipas.go.id'},
    {'nama': 'RIZQI TRI WIJAYANTI', 'email': 'rizqi.tri@kemenimipas.go.id'},
    {'nama': 'RIZQI ULYA ARIESTA', 'email': 'rizqi.ulya@kemenimipas.go.id'},
    {'nama': 'RIZQI WALDY BUAMONA', 'email': 'rizqi.waldy@kemenimipas.go.id'},
    {'nama': 'RIZQI WIJAYA', 'email': 'rizqi.wijaya98@kemenimipas.go.id'},
    {'nama': 'RIZQI ZULKARNAIN', 'email': 'rizqi.zulkarnain92@kemenimipas.go.id'},
    {'nama': 'RIZQIA SACHARINA', 'email': 'rizqia.sacharina@kemenimipas.go.id'},
    {'nama': "RIZQIYATUS SA'ADAH", 'email': 'rizqiyatus.saadah02@kemenimipas.go.id'},
    {'nama': 'RIZQO LAILA NUZULLA', 'email': 'rizqo.laila@kemenimipas.go.id'},
    {'nama': 'RIZQO SATRIA ALAM', 'email': 'rizqo.satria.alam93@kemenimipas.go.id'},
    {'nama': 'RIZQON ADHIIMU', 'email': 'rizqon.adhiimu05@kemenimipas.go.id'},
    {'nama': 'RIZQ ADYATMA SINULINGGA', 'email': 'rizqsinulingga45@gmail.com'},
    {'nama': 'RIZQY DWI NURROCHMAN', 'email': 'rizqy.dwi.nurrochman99@kemenimipas.go.id'},
    {'nama': 'RIZQY HIDAYAT LATUKAU', 'email': 'rizqy.hidayat.latukau00@kemenimipas.go.id'},
    {'nama': 'RIZQY KARYANDI AMALIA', 'email': 'rizqy.karyandi@kemenimipas.go.id'},
    {'nama': 'RIZQY VEGA PRATAMA', 'email': 'rizqy.vega@kemenimipas.go.id'},
    {'nama': 'RIZTI RIADI', 'email': 'rizti.riadi@kemenimipas.go.id'},
    {'nama': 'RIZWAN BIN KHAMIS', 'email': 'rizwan.bin.khamis98@kemenimipas.go.id'},
    {'nama': 'RIZWAN RIZKI PUTRA', 'email': 'rizwan.rizki@kemenimipas.go.id'},
    {'nama': 'RIZWAN SUANDI', 'email': 'rizwan.suandi82@kemenimipas.go.id'},
    {'nama': 'RIZWAN', 'email': 'rizwan@kemenimipas.go.id'},
    {'nama': 'RIZWANA DIAZ HAYUNING GITA', 'email': 'rizwana.diaz.hayuning.gita01@kemenimipas.go.id'},
    {'nama': 'RIZWAR AMIN', 'email': 'rizwar.amin05@kemenimipas.go.id'},
    {'nama': 'RIZYA BEELYADA PUALILLIN', 'email': 'rizya.beelyada.pualillin06@kemenimipas.go.id'},
    {'nama': 'RIZYANA AMANTIDINDA', 'email': 'rizyana.amantidinda05@kemenimipas.go.id'},
    {'nama': 'RIZZA KURNIAWAN', 'email': 'rizza.kurniawan90@kemenimipas.go.id'},
    {'nama': 'RIZZA NURKHARISMA RACHMAT, S.T', 'email': 'rizza.nurkharisma@kemenimipas.go.id'},
    {'nama': 'RIZZAL ARBI FANANI', 'email': 'rizzal.arbi@kemenimipas.go.id'},
    {'nama': 'RM. ALVIAN AZIZ', 'email': 'rm.alvian.aziz01@kemenimipas.go.id'},
    {'nama': 'RM DWI SOERYO POETRO', 'email': 'rm.dwi.soeryo.poetro80@kemenimipas.go.id'},
    {'nama': 'RMS.ALDIANSYAH', 'email': 'rms.aldiansyah95@kemenimipas.go.id'},
    {'nama': 'RO ASI CARLOS MANGAPUL MANURUNG', 'email': 'ro.asi.carlos.mangapul.manurung02@kemenimipas.go.id'},
    {'nama': 'ROARGA RUBBERT SIAHAAN, S.E.', 'email': 'roarga.rubbert@kemenimipas.go.id'},
    {'nama': 'ROAS SHADIQI', 'email': 'roas.shadiqi99@kemenimipas.go.id'},
    {'nama': 'ROBBI ABDI WIGUNA', 'email': 'robbi.abdi.wiguna93@kemenimipas.go.id'},
    {'nama': 'ROBBI MUHAMMAD ILHAMI', 'email': 'robbi.muhammad.ilhami97@kemenimipas.go.id'},
    {'nama': 'ROBBI RIVANDI', 'email': 'robbi.rivandi98@kemenimipas.go.id'},
    {'nama': 'ROBBI YATULLAH', 'email': 'robbi.yatullah@kemenimipas.go.id'},
    {'nama': 'ROBBY ADHA HARDIANTO', 'email': 'robby.adha.hardianto00@kemenimipas.go.id'},
    {'nama': 'ROBBY ADRIANSYAH SIREGAR', 'email': 'robby.adriansyah.siregar85@kemenimipas.go.id'},
    {'nama': 'ROBBY ADRIANSYAH', 'email': 'robby.adriansyah971@kemenimipas.go.id'},
    {'nama': 'ROBBY ANUGERAH SUCIPTO', 'email': 'robby.anugerah.sucipto97@kemenimipas.go.id'},
    {'nama': 'ROBBY ANUGRAH AMANDA', 'email': 'robby.anugrah.amanda94@kemenimipas.go.id'},
    {'nama': 'ROBBY ARDINATA, S.E.', 'email': 'robby.ardinata89@kemenimipas.go.id'},
    {'nama': 'ROBBY ARMUNANTO, S.E.', 'email': 'robby.armunanto@kemenimipas.go.id'},
    {'nama': 'ROBBY BERNAND SIJABAT', 'email': 'robby.bernand.sijabat83@kemenimipas.go.id'},
    {'nama': 'ROBBY CHANDRA', 'email': 'robby.chandra98@kemenimipas.go.id'},
    {'nama': 'ROBBY FEBRINALDI', 'email': 'robby.febrinaldi99@kemenimipas.go.id'},
    {'nama': 'ROBBY FERDIANSYAH ARIF', 'email': 'robby.ferdiansyah.arif03@kemenimipas.go.id'},
    {'nama': 'ROBBY HARVIANDI RAHMAN', 'email': 'robby.harviandi.rahman90@kemenimipas.go.id'},
    {'nama': 'ROBBY KRISNA PRAHMADIKA', 'email': 'robby.krisna.prahmadika92@kemenimipas.go.id'},
    {'nama': 'ROBBY KURNIA PUTRA', 'email': 'robby.kurnia.putra95@kemenimipas.go.id'},
    {'nama': 'ROBBY KURNIAWAN ZEKRI', 'email': 'robby.kurniawan.zekri95@kemenimipas.go.id'},
    {'nama': 'ROBBY KURNIAWAN', 'email': 'robby.kurniawan98@kemenimipas.go.id'},
    {'nama': 'ROBBY LOMBOAN', 'email': 'robby.lomboan@kemenimipas.go.id'},
    {'nama': 'ROBBY MARLEY', 'email': 'robby.marley99@kemenimipas.go.id'},
    {'nama': 'ROBBY MARTEJA', 'email': 'robby.marteja@kemenimipas.go.id'},
    {'nama': 'ROBBY MULIADI', 'email': 'robby.muliadi86@kemenimipas.go.id'},
    {'nama': 'ROBBY MUSTIKA', 'email': 'robby.mustika86@kemenimipas.go.id'},
    {'nama': 'ROBBY NOVRIYAN', 'email': 'robby.novriyan@kemenimipas.go.id'},
    {'nama': 'ROBBY PRAPTA YEZA', 'email': 'robby.prapta.yeza03@kemenimipas.go.id'},
    {'nama': 'ROBBY PRIMARIZAL', 'email': 'robby.primarizal@kemenimipas.go.id'},
    {'nama': 'ROBBY RAHMAN', 'email': 'robby.rahman99@kemenimipas.go.id'},
    {'nama': 'ROBBY ROBBANY', 'email': 'robby.robbany@kemenimipas.go.id'},
    {'nama': 'ROBBY SAFARI HADI', 'email': 'robby.safari@kemenimipas.go.id'},
    {'nama': 'ROBBY SASTRA', 'email': 'robby.sastra@kemenimipas.go.id'},
    {'nama': 'ROBBY SOEDARSONO', 'email': 'Robby.Soedarsono@kemenimipas.go.id'},
    {'nama': 'ROBBY SYAHPUTRA, S.Tr.Im', 'email': 'robby.syahputra99@kemenimipas.go.id'},
    {'nama': 'ROBBY TARIGAN', 'email': 'robby.tarigan82@kemenimipas.go.id'},
    {'nama': 'ROBBY TRI PANGESTU', 'email': 'robby.tri.pangestu00@kemenimipas.go.id'},
    {'nama': 'ROBBY TRISNO HADHI', 'email': 'robby.trisno@kemenimipas.go.id'},
    {'nama': 'ROBBY TRIYANTO. S', 'email': 'robby.triyanto@kemenimipas.go.id'},
    {'nama': 'ROBBY', 'email': 'robby80@kemenimipas.go.id'},
    {'nama': 'ROBBY', 'email': 'robby84@kemenimipas.go.id'},
    {'nama': 'ROBBYANOOR', 'email': 'robbyanoor@kemenimipas.go.id'},
    {'nama': 'ROBERMAN IMANUEL MANIK', 'email': 'roberman.imanuel.manik87@kemenimipas.go.id'},
    {'nama': 'ROBERT ALIDANI', 'email': 'robert.alidani@kemenimipas.go.id'},
    {'nama': 'ROBERT GUTIAWARMAN', 'email': 'robert.gutiawarman@kemenimipas.go.id'},
    {'nama': 'ROBERT JEK SOKOI', 'email': 'robert.jek.sokoi82@kemenimipas.go.id'},
    {'nama': 'ROBERT E JOHANIS', 'email': 'robert.johanis@kemenimipas.go.id'},
    {'nama': 'ROBERT NATALIUS TIBA', 'email': 'robert.nataliustiba@kemenimipas.go.id'},
    {'nama': 'ROBERT PARJUANGAN MARBUN', 'email': 'robert.parjuangan@kemenimipas.go.id'},
    {'nama': 'ROBERT PASKALIS KATIOP', 'email': 'Robert.Paskalis@kemenimipas.go.id'},
    {'nama': 'ROBERT PRATAMA ANJER DIMAS SAPUTRO', 'email': 'robert.pratama.anjer.dimas.saputro00@kemenimipas.go.id'},
    {'nama': 'ROBERT RAYKE', 'email': 'robert.rayke89@kemenimipas.go.id'},
    {'nama': 'ROBERT SANDRIA', 'email': 'robert.sandria@kemenimipas.go.id'},
    {'nama': 'ROBERT SIHALOHO', 'email': 'Robert.sihaloho@kemenimipas.go.id'},
    {'nama': 'ROBERT SINAGA', 'email': 'robert.sinaga79@kemenimipas.go.id'},
    {'nama': 'ROBERT STILMAN BILL ASBANU', 'email': 'robert.stilman@kemenimipas.go.id'},
    {'nama': 'ROBERT WIJAYA', 'email': 'robert.wijaya97@kemenimipas.go.id'},
    {'nama': 'ROBERT WILHEM DERRY', 'email': 'robert.wilhem.derry70@kemenimipas.go.id'},
    {'nama': 'ROBERTA RINI ISYUNTI', 'email': 'roberta.rini.isyunti70@kemenimipas.go.id'},
    {'nama': 'ROBERTH HERMAN KARSTEN', 'email': 'roberth.herman@kemenimipas.go.id'},
    {'nama': 'ROBERTH MALWEWAN', 'email': 'roberth.malwewan@kemenimipas.go.id'},
    {'nama': 'ROBERTH MASSA', 'email': 'roberth.massa85@kemenimipas.go.id'},
    {'nama': 'ROBERTHO FRANS KAISIEPO', 'email': 'robertho.frans.kaisiepo98@kemenimipas.go.id'},
    {'nama': 'ROBERTO ALI', 'email': 'roberto.ali95@kemenimipas.go.id'},
    {'nama': 'ROBERTO APRILIDAR FAUZI', 'email': 'roberto.aprilidar.fauzi99@kemenimipas.go.id'},
    {'nama': 'ROBERTO CAETANO FERREIRA PINTO', 'email': 'roberto.caetano.ferreira.pinto94@kemenimipas.go.id'},
    {'nama': 'ROBERTO CHRISTOV OGI ', 'email': 'roberto.christov.ogi99@kemenimipas.go.id'},
    {'nama': 'ROBERTO DHURAN DHURAN', 'email': 'roberto.dhuran.dhuran97@kemenimipas.go.id'},
    {'nama': 'ROBERTO G. MANEK LIURAI', 'email': 'roberto.g.manek.liurai00@kemenimipas.go.id'},
    {'nama': 'ROBERTO NAIBAHO', 'email': 'roberto.naibaho97@kemenimipas.go.id'},
    {'nama': 'ROBERTO SIAHAYA', 'email': 'roberto.siahaya76@kemenimipas.go.id'},
    {'nama': 'ROBERTO SITANGGANG', 'email': 'roberto.sitanggang97@kemenimipas.go.id'},
    {'nama': 'ROBERTO SULANDRY', 'email': 'roberto.sulandry83@kemenimipas.go.id'},
    {'nama': 'ROBERTO TONAPA LINO', 'email': 'roberto.tonapa.lino98@kemenimipas.go.id'},
    {'nama': 'ROBERTON LUMBAN RAJA', 'email': 'roberton.lumban.raja93@kemenimipas.go.id'},
    {'nama': 'ROBERTSON ROY RUMAYAUW', 'email': 'robertson.roy.rumayauw78@kemenimipas.go.id'},
    {'nama': 'ROBERTUS BELARMINO MELE', 'email': 'robertus.belarmino.mele89@kemenimipas.go.id'},
    {'nama': 'ROBERTUS DANANG SUBROTO', 'email': 'robertus.danang.subroto99@kemenimipas.go.id'},
    {'nama': 'ROBERTUS FERDIAN AUGUS SIDHARTA', 'email': 'Robertus.ferdian@kemenimipas.go.id'},
    {'nama': 'ROBERTUS IWAN BUDIARTO', 'email': 'robertus.iwan@kemenimipas.go.id'},
    {'nama': 'ROBERTUS KUTANGGAS', 'email': 'robertus.kutanggas74@kemenimipas.go.id'},
    {'nama': 'ROBERTUS WIJAYA', 'email': 'robertus.wijaya@kemenimipas.go.id'},
    {'nama': 'ROBET KINASIH', 'email': 'robet.kinasih94@kemenimipas.go.id'},
    {'nama': 'ROBI ABDI WIRANATA KRAMA', 'email': 'robi.abdi@kemenimipas.go.id'},
    {'nama': 'ROBI EKA SAPUTRA', 'email': 'robi.eka@kemenimipas.go.id'},
    {'nama': 'ROBI FIRDAUS', 'email': 'robi.firdaus@kemenimipas.go.id'},
    {'nama': 'ROBI GUNAWAN PURBA', 'email': 'robi.gunawan.purba98@kemenimipas.go.id'},
    {'nama': 'ROBI HERMAWAN SUSANTO', 'email': 'robi.hermawan.susanto00@kemenimipas.go.id'},
    {'nama': 'ROBI HIDAYAT', 'email': 'robi.hidayat89@kemenimipas.go.id'},
    {'nama': 'ROBI ILYASA', 'email': 'robi.ilyasa03@kemenimipas.go.id'},
    {'nama': 'ROBI IRAWAN', 'email': 'robi.irawan88@kemenimipas.go.id'},
    {'nama': 'MUHAMMAD ROBI MAULANA', 'email': 'robi.maulana@kemenimipas.go.id'},
    {'nama': 'ROBI RAHMADI', 'email': 'robi.rahmadi86@kemenimipas.go.id'},
    {'nama': 'ROBI SANDI AKBAR', 'email': 'robi.sandi@kemenimipas.go.id'},
    {'nama': 'ROBI SETIAJI', 'email': 'robi.setiaji97@kemenimipas.go.id'},
    {'nama': 'ROBI SETIAWAN TRIDESIA', 'email': 'robi.setiawan.tridesia97@kemenimipas.go.id'},
    {'nama': 'ROBI SUGARA', 'email': 'robi.sugara97@kemenimipas.go.id'},
    {'nama': 'ROBI SYAPUTRA', 'email': 'robi.syaputra99@kemenimipas.go.id'},
    {'nama': 'ROBI WAHYUDI', 'email': 'robi.wahyudi@kemenimipas.go.id'},
    {'nama': 'ROBI WIBAWA WINATA', 'email': 'robi.wibawa@kemenimipas.go.id'},
    {'nama': 'ROBI YUHENDRI, A.Md', 'email': 'robi.yuhendri81@kemenimipas.go.id'},
    {'nama': 'ROBI', 'email': 'robi89@kemenimipas.go.id'},
    {'nama': 'ROBI', 'email': 'robi90@kemenimipas.go.id'},
    {'nama': 'ROBIANTA BARUS', 'email': 'robianta.barus97@kemenimipas.go.id'},
    {'nama': 'ROBIANTO, S.H', 'email': 'robianto71@kemenimipas.go.id'},
    {'nama': 'ROBIANUR', 'email': 'robianur93@kemenimipas.go.id'},
    {'nama': 'ROBIE SANJAYA', 'email': 'robie.sanjaya03@kemenimipas.go.id'},
    {'nama': 'ROBIL', 'email': 'robil94@kemenimipas.go.id'},
    {'nama': 'ROBIN AGUSSAPUTRA', 'email': 'robin.agussaputra@kemenimipas.go.id'},
    {'nama': 'ROBIN HASIHOLAN HUTABARAT', 'email': 'robin.hasiholan.hutabarat92@kemenimipas.go.id'},
    {'nama': 'ROBIN PUTUT HATTARI ARDRIYUNAN', 'email': 'robin.putut.hattari.ardriyunan90@kemenimipas.go.id'},
    {'nama': 'ROBIN SIMAMORA', 'email': 'robin.simamora67@kemenimipas.go.id'},
    {'nama': 'ROBIN ZYU AKBAR', 'email': 'robin.zyu.akbar96@kemenimipas.go.id'},
    {'nama': 'ROBIN', 'email': 'robin96@kemenimipas.go.id'},
    {'nama': 'ROBINSAR BANJAR NAHOR', 'email': 'robinsar.banjar.nahor95@kemenimipas.go.id'},
    {'nama': 'ROBINSON ALEXANDER KALE', 'email': 'robinson.alexander@kemenimipas.go.id'},
    {'nama': 'ROBINSON HASUDUNGAN SIREGAR', 'email': 'robinson.hasudungan@kemenimipas.go.id'},
    {'nama': 'ROBINSON PERANGIN ANGIN', 'email': 'robinson.perangin@kemenimipas.go.id'},
    {'nama': 'ROBINSON SINURAT', 'email': 'robinson.sinurat@kemenimipas.go.id'},
    {'nama': 'ROBINSON SUFARNO MADJOWA', 'email': 'robinson.sufarno.madjowa96@kemenimipas.go.id'},
    {'nama': 'ROBINSON TAMPUBOLON', 'email': 'robinson.tampubolon@kemenimipas.go.id'},
    {'nama': 'ROBINSON TULONG', 'email': 'robinson.tulong@kemenimipas.go.id'},
    {'nama': 'ROBINSON, SE', 'email': 'robinson91@kemenimipas.go.id'},
    {'nama': 'ROBINSON', 'email': 'robinson97@kemenimipas.go.id'},
    {'nama': 'ROBINTANG GANDA TUA SITORUS', 'email': 'robintang.ganda.tua.sitorus05@kemenimipas.go.id'},
    {'nama': 'ROBITA ISLAMI', 'email': 'robita.islami91@kemenimipas.go.id'},
    {'nama': 'ROBITHOH ANAM ULINNAJA', 'email': 'robithoh.anam@kemenimipas.go.id'},
    {'nama': 'ROBIY FANCANDRA', 'email': 'robiy.fancandra98@kemenimipas.go.id'},
    {'nama': 'ROBIYANTORO', 'email': 'robiyantoro90@kemenimipas.go.id'},
    {'nama': 'ROBIYANUR', 'email': 'robiyanur94@kemenimipas.go.id'},
    {'nama': 'ROBY AFRIADI', 'email': 'roby.afriadi87@kemenimipas.go.id'},
    {'nama': 'ROBY AGI PUTRA', 'email': 'roby.agi.putra00@kemenimipas.go.id'},
    {'nama': 'ROBY AKBAR WANARDI', 'email': 'roby.akbar.wanardi98@kemenimipas.go.id'},
    {'nama': 'ROBY ALDYANTO', 'email': 'roby.aldyanto94@kemenimipas.go.id'},
    {'nama': 'ROBY ARYANTO', 'email': 'roby.aryanto97@kemenimipas.go.id'},
    {'nama': 'ROBY AZHARI', 'email': 'roby.azhari@kemenimipas.go.id'},
    {'nama': 'ROBY CHRISTIAN HUTASOIT', 'email': 'roby.christian.hutasoit98@kemenimipas.go.id'},
    {'nama': 'ROBY EDUARD THERIK', 'email': 'roby.eduard@kemenimipas.go.id'},
    {'nama': 'ROBY FERNANDEZ', 'email': 'roby.fernandez@kemenimipas.go.id'},
    {'nama': 'ROBY FIRLANA', 'email': 'roby.firlana99@kemenimipas.go.id'},
    {'nama': 'ROBY GINANZAR TIRTA PRAWIRA', 'email': 'roby.ginanzar.tirta.prawira91@kemenimipas.go.id'},
    {'nama': 'ROBY HARDIANSYAH', 'email': 'roby.hardiansyah@kemenimipas.go.id'},
    {'nama': 'ROBY IKHSAN', 'email': 'roby.ikhsan78@kemenimipas.go.id'},
    {'nama': 'ROBY KURNIAWAN', 'email': 'roby.kurniawan800@kemenimipas.go.id'},
    {'nama': 'ROBY NUANSA', 'email': 'roby.nuansa92@kemenimipas.go.id'},
    {'nama': 'ROBY PARDOMUAN CIBRO, S.E.', 'email': 'roby.pardomuan@kemenimipas.go.id'},
    {'nama': 'ROBY ROZALI', 'email': 'roby.rozali@kemenimipas.go.id'},
    {'nama': 'ROBY TRI NUGROHO', 'email': 'roby.tri.nugroho95@kemenimipas.go.id'},
    {'nama': 'ROCHANA ERNAWATI', 'email': 'rochana.ernawati70@kemenimipas.go.id'},
    {'nama': 'ROCHMAD NUR KHOLIS', 'email': 'rochmad.nur.kholis97@kemenimipas.go.id'},
    {'nama': 'ROCHMAD SAHID, S.E.,M.A.P.', 'email': 'rochmad.sahid@kemenimipas.go.id'},
    {'nama': 'ROCHMAD SEDIJONO', 'email': 'rochmad.sedijono68@kemenimipas.go.id'},
    {'nama': 'ROCHMAN NUGROHO', 'email': 'rochman.nugroho95@kemenimipas.go.id'},
    {'nama': 'ROCHMANI WIKA HASTUNINGRUM', 'email': 'rochmani.wika.hastuningrum93@kemenimipas.go.id'},
    {'nama': 'ROCHUS GONSALEZ NANDO BANA', 'email': 'rochus.gonsalez.nando.bana97@kemenimipas.go.id'},
    {'nama': 'ROCHY NANANG SAPUTRA', 'email': 'rochy.nanang.saputra68@kemenimipas.go.id'},
    {'nama': 'ROCKY FEBRIAN', 'email': 'rocky.febrian05@kemenimipas.go.id'},
    {'nama': 'ROCKY FRIEZA', 'email': 'rocky.frieza01@kemenimipas.go.id'},
    {'nama': 'ROCKY JAYA SAPUTRA', 'email': 'rocky.jaya@kemenimipas.go.id'},
    {'nama': 'ROCKY LARENGGAM', 'email': 'rocky.larenggam@kemenimipas.go.id'},
    {'nama': 'ROCKY MARCIANO SINE', 'email': 'rocky.marciano@kemenimipas.go.id'},
    {'nama': 'ROCKY MARKIANO BANGUN', 'email': 'rocky.markiano@kemenimipas.go.id'},
    {'nama': 'ROCKY OKTAVIANUS MISDJAN', 'email': 'rocky.oktavianus@kemenimipas.go.id'},
    {'nama': 'ROCKY RIVALDO', 'email': 'rocky.rivaldo97@kemenimipas.go.id'},
    {'nama': 'ROCKY ROLAND BUNGSU LAY', 'email': 'rocky.roland.bungsu.lay92@kemenimipas.go.id'},
    {'nama': 'ROCKY SIMANJUNTAK', 'email': 'rocky.simanjuntak97@kemenimipas.go.id'},
    {'nama': 'ROCKY WAJONG', 'email': 'rocky.wajong@kemenimipas.go.id'},
    {'nama': 'RODASNI SIDAURUK', 'email': 'rodasni.sidauruk91@kemenimipas.go.id'},
    {'nama': 'RODESTA DEVEGA KEHI', 'email': 'rodesta.kehi@kemenimipas.go.id'},
    {'nama': 'RODHAN BIJAKSA', 'email': 'rodhan.bijaksa94@kemenimipas.go.id'},
    {'nama': 'RODHIATI SIREGAR', 'email': 'rodhiati.siregar@kemenimipas.go.id'},
    {'nama': 'RODHIYA NOOR FAJRI', 'email': 'rodhiya.noor@kemenimipas.go.id'},
    {'nama': 'RODHIYATNO', 'email': 'rodhiyatno74@kemenimipas.go.id'},
    {'nama': 'RODI ERNADO', 'email': 'rodi.ernado@kemenimipas.go.id'},
    {'nama': 'RODIAH', 'email': 'rodiah85@kemenimipas.go.id'},
    {'nama': 'RODIAN, S.H.', 'email': 'rodian89@kemenimipas.go.id'},
    {'nama': 'RODIATUL MARDIYAH', 'email': 'rodiatul.mardiyah95@kemenimipas.go.id'},
    {'nama': 'RODIYAH', 'email': 'rodiyah68@kemenimipas.go.id'},
    {'nama': 'RODJOSH TIO PUTRA L. TOBING', 'email': 'rodjosh.tio.putra.l.tobing98@kemenimipas.go.id'},
    {'nama': 'RODLIN, S.E.', 'email': 'rodlin88@kemenimipas.go.id'},
    {'nama': 'RODY AHMAD TOYIB', 'email': 'rody.ahmad.toyib00@kemenimipas.go.id'},
    {'nama': 'RODY WARDANIAL', 'email': 'rody.wardanial@kemenimipas.go.id'},
    {'nama': 'ROECY RANTIKA', 'email': 'roecy.rantika@kemenimipas.go.id'},
    {'nama': 'ROFI HANSYAH', 'email': 'rofi.hansyah@kemenimipas.go.id'}
]
